### DISCUSSION TITLE
Should we have a Action to check translation progress?

### DISCUSSION THREAD

**Discussion by lixw1021** [crowdin/github-action#107] [Ideas]
Hey Crowdin team. 
Our team used the CLI on Team City and want to transfer to Github actions, we used to have a python script to check if the translation status is 100% before downloading the translation. This will block the PR merge if the translation is not complete. Do you think we can have an Action to check the progress?

**Comment by DimaYashchyshyn-zz** [comment]
Hi, well, I guess yes, but why wouldn't you try a native connector? It supports patterns like "export only 100% translated file" and/or "export only 100% approved file" out of the box

**Reply by lixw1021** [reply]
Thanks @DimaYashchyshyn ,
I am still trying to upload the source and haven't test download, 
Do you mean to use `export_only_approved: true` and the download action will fail if there are translations not finished.

**Comment by DimaYashchyshyn-zz** [comment]
Well, almost, it would export only approved stings and would skip untranslated and translated. Often it's used in combination with "skip untranslated files", so as a result you receive 100% approved files only

**Comment by zvictor** [comment]
In my case I am interested in not letting a new deployment happen unless the translations are done.
I rather keep my services outdated than let them have incomplete translations.

Is it possible to have the action exiting with error with any translation is missing?

**Reply by DimaYashchyshyn** [reply]
Have you tried a setup "export only approved = true"?
https://github.com/marketplace/actions/crowdin-action#supported-options
this will export only fully reviewed suggestions, the approved ones

**Reply by andrii-bodnar** [reply]
@zvictor please check this answer - https://github.com/crowdin/github-action/discussions/107#discussioncomment-5321782

**Comment by andrii-bodnar** [comment]
You can use an additional step with Crowdin CLI for that:

```yml
name: Crowdin sync
on:
  workflow_dispatch:

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Crowdin CLI
        run: npm i -g @crowdin/cli

      - name: Check progress
        run: crowdin status translation --fail-if-incomplete 

      # other steps
```

the `Check progress` step **will fail** if the Crowdin project is not fully translated. 

The same is relevant for a single language: `crowdin status translation --fail-if-incomplete -l uk`
