### DISCUSSION TITLE
Unable to get my upload_sources config working

### DISCUSSION THREAD

**Discussion by henieek** [crowdin/github-action#156] [Q&A] [answered]
Hey all,

I'm trying to set up the Github Action to only upload sources (we have our own script that we use for downloading translations). I however encountered an obstacle that I'm unable to proceed through.

Here's my github workflow:

```yaml
name: Crowdin Action

on:
  push:
    branches: [ main ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: crowdin action
      uses: crowdin/github-action@1.5.2
      with:
        upload_sources: true
        upload_translations: false
        download_translations: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

and here's my `crowdin.yml`, which I keep in repository's root directory:

```yaml
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: false
files:
  - source: app/src/main/res/values/*.xml
    translation: app/src/main/res/values-%two_letters_code%/%original_file_name%.xml
    translate_attributes: 0
  - source: iosStrings/en/ios_imessage.strings
    translation: iosStrings/values-%two_letter_code%/ios_imessage.strings
    translate_attributes: 0
```

My understanding is that the Github Action will detect I have a config file in my repo and will use it.

Unfortunately the workflow fails to run with the following message:

```
STARTING CROWDIN ACTION
UPLOAD SOURCES
❌ Configuration file is invalid. Check the following parameters in your configuration file:
	- 'Translation' parameter should contain at least one language placeholder (e.g. %locale%)
```

Could you please help me understand what I'm doing wrong?

Thanks in advance!

**Comment by andrii-bodnar** [comment, marked as answer]
Hi @henieek,

there is an error in the second file's group config - `two_letter_code` instead of `two_letters_code`

Here is the correct `crowdin.yml` configuration:

```yml
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: false
files:
  - source: app/src/main/res/values/*.xml
    translation: app/src/main/res/values-%two_letters_code%/%original_file_name%.xml
    translate_attributes: 0
  - source: iosStrings/en/ios_imessage.strings
    translation: iosStrings/values-%two_letters_code%/ios_imessage.strings
    translate_attributes: 0

```
