### DISCUSSION TITLE
How do I use Pre-translation ?

### DISCUSSION THREAD

**Discussion by wei18** [crowdin/github-action#168] [Q&A] [answered]
I would like to do the following CMD on Github Action, and I didn't see any parameters in action.yml
```
# To run pre-translation via TM:
crowdin pre-translate --method tm
```

### REF:
- https://support.crowdin.com/enterprise/pre-translation/
- https://developer.crowdin.com/cli-tool/#pre-translation

**Comment by andrii-bodnar** [comment, marked as answer]
Hi @Wei18,

currently, this Action doesn't support running the `pre-translate` CLI command but you can use the following approach to run any command including Pre-Translation:

```yml
name: Run crowdin cli command

on:
  workflow_dispatch:

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Crowdin CLI
        run: npm i -g @crowdin/cli

      - name: Run command
        run: crowdin -V
```

Result:

![Знімок екрана 2023-03-02 о 09 40 18](https://user-images.githubusercontent.com/29282228/222362765-368261a0-710d-4cfc-8fa3-ab4fe49e8ae0.png)
