### DISCUSSION TITLE
Sync source from crowdin

### DISCUSSION THREAD

**Discussion by igorkova** [crowdin/github-action#172] [Q&A]
Is there a possibility to sync source from crowdin?

If someone changes source string in crowdin, can we have it pulled down in a PR. I guess I'm after `download_sources` same as we have for translations.

**Comment by andrii-bodnar** [comment]
Yes, it's possible via the `download_sources` option. It works in the same way as with the translations download.

You can also combine this option with the `download_translations` option and the Action will create a PR that includes both sources and translations from Crowdin.

**Comment by igorkova** [comment]
Thanks for a quick reply.

I tried it now and have hit a bug described here https://github.com/crowdin/github-action/issues/166

**Reply by andrii-bodnar** [reply]
Could you please provide your full Crowdin GH Action configuration + `crowdin.yml` (without credentials) + actual/expected results? Thanks.

**Comment by igorkova** [comment]
```
name: Translations Sync

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Crowdin sync
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          download_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action]'
          pull_request_base_branch_name: 'main'

          # Sources pattern
          source: src/locales/en/messages.po
          # Translations pattern
          translation: src/locales/%two_letters_code%/messages.po

          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Reply by igorkova** [reply]
There is no crowdin.yml (as you can see we used action without crowdin.yml)

**Reply by andrii-bodnar** [reply]
thank you!

What about actual and expected results? If your repo is public, it would be great to get a link

**Reply by igorkova** [reply]
Unfortunately, repo is private.

Actual result: source messages.po is downloaded to the root of our repo
Expected result: source messages.po is downloaded to the path defined in source: src/locales/en/messages.po

**Reply by andrii-bodnar** [reply]
@igorkova what is the source files structure of your Crowdin project?

**Reply by igorkova** [reply]
There was no structure set by me initially. 
I created empty project.
Used github action and GH action pushed files. All files were pushed in a root on Crowdin

Disclaimer, initial GH action did not had `download_sources: true` but everything else was there.

**Reply by andrii-bodnar** [reply]
So, as I understood correctly, you only have the `messages.po` inside of your Crowdin project, and there are no directories like `src` > `locales` > `en`, right?

**Reply by igorkova** [reply]
That is correct.
That's how action pushed it initially, on the initial run.
<img width="1020" alt="Screenshot 2023-03-24 at 13 25 56" src="https://user-images.githubusercontent.com/3902581/227520785-4aaf2fa2-f698-4357-83ef-69ffc803047f.png">

**Reply by andrii-bodnar** [reply]
@igorkova got it, thank you! To make it download the source file correctly, you will need the `crowdin.yml` configuration file with specifier [`"preserve_hierarchy": true`](https://developer.crowdin.com/configuration-file/#saving-directory-structure-on-server) inside.

By default, the `preserce_hierarchy` is `false` so the intermediate directories are skipped by CLI during source files upload. On the other hand, it's important for the `download sources` command.

So, if you need to use the download sources functionality, you need to have the `yml` configuration file with the `preserve_hierarchy` set to `true`. This way the source files structure in the Crowdin project will be the same as your local structure and the download sources functionality will work correctly. This will require a source file re-upload.

In the nearest future, we are going to add a possibility to pass the `preserve-hierarchy` option via CLI command parameters, so this workflow will become possible even without the `crowdin.yml` config file.

**Reply by igorkova** [reply]
How should crowdin.yml look like? Can you give example?

**Reply by igorkova** [reply]
My crowdin.yml
```
"preserve_hierarchy": true
```
It's in the root of my repo

However, doesn't seem to be working. I still see this in the GH action output:
```
DOWNLOAD SOURCES
⚠️  Because the 'preserve_hierarchy' parameter is set to 'false':
	- CLI might download some unexpected files that match the pattern;
	- Source file hierarchy may not be preserved and will be the same as in Crowdin.
✔️  Fetching project info
✔️  File 'messages.po'
```

**Reply by andrii-bodnar** [reply]
sure, something like that:

**crowdin.yml:**

```yml
"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "src/locales/en/messages.po",
    "translation": "src/locales/%two_letters_code%/messages.po"
  }
]

```

**workflow step:**

```yml
- name: Crowdin sync
  uses: crowdin/github-action@v1
  with:
    upload_sources: true
    download_sources: true
    upload_translations: false
    download_translations: true
    localization_branch_name: l10n_crowdin_translations
    create_pull_request: true
    pull_request_title: 'New Crowdin Translations'
    pull_request_body: 'New Crowdin translations by [Crowdin GH Action]'
    pull_request_base_branch_name: 'main'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
    CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```
