### DISCUSSION TITLE
Problems with sync

### DISCUSSION THREAD

**Discussion by EveryDayRains** [crowdin/github-action#175] [Q&A]
Hi, I need to update my repository. But there is an error at the event. Uploading to crowdin works, but pull doesn't. What is the problem?
log
```
STARTING CROWDIN ACTION
UPLOAD SOURCES
❌ Configuration file doesn't exist. Run the 'crowdin init' to generate configuration skeleton
```

workflow file
```yml
 name: Sync locales

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'


jobs:
  synccrowdin:
    name: Sync repo from Crowdin
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: crowdin/github-action@v1
        with:
          config: ./crowdin.yml
          download_translations: true
          localization_branch_name: crowdin-stage
          skip_untranslated_strings: true
          skip_untranslated_files: true
          export_only_approved: true
          commit_message: 'New Crowdin translations'

          create_pull_request: true
          pull_request_title: 'New Crowdin translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_labels: 'enhancement'
          pull_request_base_branch_name: 'main'


        env:
          GITHUB_TOKEN: ${{ secrets.BoticordAC_TOKEN }}
          GITHUB_ACTOR: BoticordAC
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```
crowdin file
```yaml
files:
  - source: /docs/**/ru/**/*
    translation: /docs/%two_letters_code%/**/%original_file_name%
  - source: /website/ru.json
    translation: /website/%two_letters_code%.json

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
```
