### DISCUSSION TITLE
Crowdin GH native integration and GH Action

### DISCUSSION THREAD

**Discussion by Nukecraft5419** [crowdin/github-action#186] [General]
Hi, but doesn't Crowdin normally already automate everything via the integration between Crowdin and GitHub I am asking whether or not I should also include this automation in the repository

**Comment by dies** [comment]
Github Action is more of an alternative way to integrate with Crowdin than the native integration. It doesn't require you to give Crowdin access to your repo, it has some more features and flexibility, like configuring who will review pull requests. However, Github Action may be more difficult to set up for some users.

**Comment by Nukecraft5419** [comment]
So if I'm not mistaken Crowdin has the limit of 1 integration for the free plan on that I still don't understand if like on another crowdin project always open to the public then it makes me do another automation or not, and if this thing with the bot is a better way to not have that limit

**Comment by dies** [comment]
There are no limits to open-source projects. You can submit this form to get a license for your open project https://crowdin.com/page/open-source-project-setup-request

Github Action integrations do not count toward the integrations limit

**Comment by Nukecraft5419** [comment]
I have noticed that with the integration of Crowdin and GitHub I have to go and synchronise myself to get the sine pulls created, it usually doesn't synchronise anything just the first time, in fact I would like to see if then using GitHub Actions this will be resolved for the open-source projects request is a good thing only it requires a site and Crowdin Enterprise in the future will

**Comment by dies** [comment]
The website field is optional. The Crowdin Enterprise organization handle is also optional. If you're using crowdin.com, just enter your username and you should be good to go

**Comment by Nukecraft5419** [comment]
What advantages would it provide?

**Comment by tatttz** [comment]
Open-source provide you with some features that aren't available in the Free plan, moreover if you have public repo, as Serhiy advised you regarding your case

**Comment by Nukecraft5419** [comment]
It filled itself in for me, i.e. the project part, the username and the email automatically taken from the account I logged in with. Then I put the repository link as the website link and the licence link as the direct link to the licence in the repository, and then as "Your name" I copied what's under the Crowdin username.

**Comment by tatttz** [comment]
Great! The main requirement is publicly available repo, so please don't forget to share the url to your repo once requesting the open-source licence

**Comment by Nukecraft5419** [comment]
In fact, I put the repo url in the site url, then I wanted to see if it is possible to get help to switch from integration to integration with GitHub Actions https://github.com/LifeMC-Studios/LifeMC/tree/main

**Reply by andrii-bodnar** [reply]
there is a guide - https://github.com/crowdin/github-action/wiki/OAuth-to-Actions-migration-guide

**Reply by Nukecraft5419** [reply]
I with the classic integration between Crowdin and GitHub had to change the various file names so giving them the name like en_gb and so on because it created them with big letters like en_GB how can I do this then if I switch to Crowdin Action

**Reply by andrii-bodnar** [reply]
@Nukecraft5419 you can configure the [Languages mapping](https://crowdin.github.io/crowdin-cli/advanced#languages-mapping-configuration) in your `crowdin.yml` configuration file for these language codes.

**Reply by Nukecraft5419** [reply]
As far as branches are concerned, classical integration usually creates a separate branch on which to do operations and then sends them via a PR to the main branch, how does it work for this one?

**Reply by andrii-bodnar** [reply]
@Nukecraft5419 It will also create a new branch. The `localization_branch_name` parameter specifies the branch name. See this video for a better understanding of how it works - https://www.youtube.com/watch?v=5b7BMuCoKGg.

**Reply by Nukecraft5419** [reply]
I tried a little bit the whole thing per se I would need the same thing that the classic integration did that is that it does pulls and so on however that it also has the language mapping that is that the final files like en_it.json en_gb.json and so on I hope you help me figure out where I went wrong the mapping is not present because it gives me error from what I understand I have to create an env with those variables as well

```
name: Crowdin Action

on:
  push:
    branches: [main]

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          localization_branch_name: l10n_main
          source: /Crowdin/lang/en_us.json
          translation: /%original_path%/%locale_with_underscore%.json

          create_pull_request: true
          pull_request_title: "New Crowdin translations"
          pull_request_body: "New Crowdin pull request with translations"
          pull_request_base_branch_name: "main"

          pull_request_labels: "enhancement, good first issue"
          pull_request_assignees: "crowdin-bot"
          pull_request_reviewers: "crowdin-user-reviewer"
          pull_request_team_reviewers: "crowdin-team-reviewer"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

**Reply by andrii-bodnar** [reply]
@Nukecraft5419 could you please clarify what is wrong? I don't understand you

**Reply by Nukecraft5419** [reply]
I don't know if I did the file as well as it needed to be done to get the desired result i.e. that of classical integration but with something more

**Reply by Nukecraft5419** [reply]
Basically if you didn't understand, I wanted to know if the way I did it is okay so it does the pulls and the various things that the classic method does but with improvements i.e. branch apart "l10n_main" where it does the various changes with the commits divided by language I think that was the classic method like en_gb (English UK) and so on and then it does a PR where it sends everything to the main I don't know if that's how I did it

**Reply by andrii-bodnar** [reply]
@Nukecraft5419 I don't see the corresponding changes in your repo. Just set up the GH Action in a separate branch and then I will see if it's ok. I need to see the GH Action run logs as well

**Reply by Nukecraft5419** [reply]
Perfect I will send the change as soon as possible in the dev_main branch

**Reply by Nukecraft5419** [reply]
I sent the commit but nothing started
https://github.com/LifeMC-Studios/LifeMC/blob/dev_main/.github/workflows/crowdin-sync.yml

**Reply by andrii-bodnar** [reply]
@Nukecraft5419 It's because your action trigger is set up for the `main` branch. 

Please refer to the:

- [OAuth to Actions migration guide](https://github.com/crowdin/github-action/wiki/OAuth-to-Actions-migration-guide)
- [Learn GitHub Actions](https://docs.github.com/en/actions/learn-github-actions)
- [Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows)
- [Encrypted secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets)

**Comment by Nukecraft5419** [comment]
I see then I send the PR to the main so the whole thing starts

**Reply by andrii-bodnar** [reply]
The configuration should be the following:

**crowdin-sync.yml**

```yml
name: Crowdin Action

on:
  push:
    branches: [main]

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_main

          create_pull_request: true
          pull_request_title: "New Crowdin translations"
          pull_request_body: "New Crowdin pull request with translations"
          pull_request_base_branch_name: "main"
          pull_request_labels: "enhancement, good first issue"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

**crowdin.yml**

```yml
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /Crowdin/lang/en_us.json
    translation: /%original_path%/%locale_with_underscore%.json
```

**Reply by Nukecraft5419** [reply]
Sorry I didn't understand so you have to keep the classic file as well?
Then the language mapping part how should it be done because to me it was giving error in fact as soon as I did the PR everything went red i.e. it didn't go successful

**Reply by Nukecraft5419** [reply]
https://github.com/LifeMC-Studios/LifeMC/actions/runs/6058901304/job/16441512539

**Reply by Nukecraft5419** [reply]
I also quoted you in the commit I did when I put the one you sent me, now I don't know why it didn't download anything and it didn't create the branch where it should do the whole thing

**Reply by Nukecraft5419** [reply]
I saw an email that strings had been added and I thought like I'm doing something else, and now I noticed that from so that is the old one that had the right position and a new one put somewhere else
![image](https://github.com/crowdin/github-action/assets/72621737/0c767daf-7a56-4684-99c3-aabd821dc349)

**Reply by andrii-bodnar** [reply]
@Nukecraft5419 try adding the `crowdin_branch_name: main` to the Action configuration and `preserve_hierarchy: true` to the `crowdin.yml` config file

**Reply by Nukecraft5419** [reply]
I did the various tests and now it failed again https://github.com/LifeMC-Studios/LifeMC/actions/runs/6069778069/job/16464686896 problem with these tests on crowdin now gives me that I have reached the limit and this is a serious problem being an open-source project

This is a mistake that is ultimately
remote: Permission to LifeMC-Studios/LifeMC.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/LifeMC-Studios/LifeMC.git/': The requested URL returned error: 403

**Reply by andrii-bodnar** [reply]
@Nukecraft5419 It's not about the limits. Please read the following part of the Action documentation:

![image](https://github.com/crowdin/github-action/assets/29282228/7a964426-30bf-4f31-868f-740c2cb408be)

**Reply by Nukecraft5419** [reply]
Not the one I mean about Crowdin the 60k limit

**Reply by Nukecraft5419** [reply]
I also got the email that within 10 days my account will be closed if I don't Upgrade

**Reply by Nukecraft5419** [reply]
It seems that I have limitations with the permissions i.e. it doesn't have access as precisely from the error I had sent how can I fix it, I saw something in the organization settings only I avoided it because I didn't know if that was what was needed

**Reply by andrii-bodnar** [reply]
@Nukecraft5419 try this:

```yml
name: Crowdin Action

on:
  push:
    branches: [main]

jobs:
  crowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_main
          crowdin_branch_name: main

          create_pull_request: true
          pull_request_title: "New Crowdin translations"
          pull_request_body: "New Crowdin pull request with translations"
          pull_request_base_branch_name: "main"
          pull_request_labels: "enhancement, good first issue"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

**Reply by Nukecraft5419** [reply]
It works, only now it gives me this, do I delete the one I had before and just use this one?

![image](https://github.com/crowdin/github-action/assets/72621737/a0da8945-7d0c-424c-bd41-c477996df58a)

**Reply by Nukecraft5419** [reply]
Then I can remove the Crowdin permissions of my GitHub account so much now I use the workflow and no longer the classic integration

**Reply by Nukecraft5419** [reply]
I saw that he made both the branch then the changes but the PR is not there, as for the 60k word limit and strange that right away I have reached it I have seen open-source projects that have a lot more words than that pier than mine which is in the beginning and they don't have a subscription and very strange

**Reply by Nukecraft5419** [reply]
![image](https://github.com/crowdin/github-action/assets/72621737/77b149ea-4ecd-424e-afff-c019b13137f1)

**Reply by tattiza** [reply]
Yes, you can have unlimited number of words, the message about hosted words limit should already be gone from your account

**Reply by Nukecraft5419** [reply]
Yes in fact, it was taken down by the Crowdin team I guess they read here, as far as the email I got of when I exceeded that limit and that if I didn't upgrade my account was suspended and then deleted within 10 days, and then as far as Crowdin Actions is concerned it's all fine just it doesn't create the PR

**Reply by Nukecraft5419** [reply]
I found these two errors

```
⚠️  Due to missing respective sources, the following translations will be omitted:
	- main/Crowdin/lang/af_za.json
	- main/Crowdin/lang/sq_al.json
	- main/Crowdin/lang/ar_sa.json
	- main/Crowdin/lang/be_by.json
	- main/Crowdin/lang/bg_bg.json
	- main/Crowdin/lang/ca_es.json
	- main/Crowdin/lang/zh_cn.json
	- main/Crowdin/lang/zh_tw.json
	- main/Crowdin/lang/hr_hr.json
	- main/Crowdin/lang/cs_cz.json
	- main/Crowdin/lang/da_dk.json
	- main/Crowdin/lang/nl_nl.json
	- main/Crowdin/lang/en_ud.json
	- main/Crowdin/lang/en_gb.json
	- main/Crowdin/lang/eo_uy.json
	- main/Crowdin/lang/et_ee.json
	- main/Crowdin/lang/fil_ph.json
	- main/Crowdin/lang/fi_fi.json
	- main/Crowdin/lang/fr_fr.json
	- main/Crowdin/lang/fr_ca.json
	- main/Crowdin/lang/ka_ge.json
	- main/Crowdin/lang/de_de.json
	- main/Crowdin/lang/de_ch.json
	- main/Crowdin/lang/el_gr.json
	- main/Crowdin/lang/he_il.json
	- main/Crowdin/lang/hi_in.json
	- main/Crowdin/lang/hu_hu.json
	- main/Crowdin/lang/is_is.json
	- main/Crowdin/lang/id_id.json
	- main/Crowdin/lang/it_it.json
	- main/Crowdin/lang/ja_jp.json
	- main/Crowdin/lang/ko_kr.json
	- main/Crowdin/lang/lv_lv.json
	- main/Crowdin/lang/it_lt.json
	- main/Crowdin/lang/lol_us.json
	- main/Crowdin/lang/ms_my.json
	- main/Crowdin/lang/no_no.json
	- main/Crowdin/lang/nn_no.json
	- main/Crowdin/lang/fa_ir.json
	- main/Crowdin/lang/en_pt.json
	- main/Crowdin/lang/pl_pl.json
	- main/Crowdin/lang/pt_pt.json
	- main/Crowdin/lang/pt_br.json
	- main/Crowdin/lang/ro_ro.json
	- main/Crowdin/lang/ru_ru.json
	- main/Crowdin/lang/sk_sk.json
	- main/Crowdin/lang/sl_si.json
	- main/Crowdin/lang/es_es.json
	- main/Crowdin/lang/es_ar.json
	- main/Crowdin/lang/sv_se.json
	- main/Crowdin/lang/tt_ru.json
	- main/Crowdin/lang/th_th.json
	- main/Crowdin/lang/tr_tr.json
	- main/Crowdin/lang/uk_ua.json
	- main/Crowdin/lang/vi_vn.json
	- main/Crowdin/lang/cy_gb.json
```



```
remote: 
remote: Create a pull request for 'l10n_main' on GitHub by visiting:        
remote:      https://github.com/LifeMC-Studios/LifeMC/pull/new/l10n_main        
remote: 
To https://github.com/LifeMC-Studios/LifeMC.git
 * [new branch]      l10n_main -> l10n_main
CHECK IF ISSET SAME PULL REQUEST
CREATE PULL REQUEST
ADD LABELS TO PULL REQUEST
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/issues/issues#update-an-issue"
}
PULL REQUEST CREATED: null
```

**Reply by andrii-bodnar** [reply]
@Nukecraft5419 as I can see, the `crowdin_branch_name: main` is missing again in your workflow configuration. Also, try removing the `pull_request_labels: "enhancement, good first issue"` - I guess the GitHub API doesn't accept that value for some reason

**Reply by Nukecraft5419** [reply]
https://github.com/LifeMC-Studios/LifeMC/blob/dev_main/.github/workflows/crowdin-sync.yml

**Reply by Nukecraft5419** [reply]
https://github.com/LifeMC-Studios/LifeMC/actions/runs/6076768932/job/16485315581

**Reply by andrii-bodnar** [reply]
@Nukecraft5419 there's still some issue with a PR creation (probably, a permission issue). Try specifying the exact commit as the Crowdin Action version to debug this:

```yml
...
uses: crowdin/github-action@6c108a7037cfdd166f8bea9ec42933d7211d30fe
...
```

This commit includes improved logging for this case.

**Reply by Nukecraft5419** [reply]
I have to put this thing inside crowdin-sync.yml

**Reply by Nukecraft5419** [reply]
So it has to be done tell me if it is okay so I send the modification

```
name: Crowdin Action

on:
  push:
    branches: [main]

jobs:
  crowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@6c108a7037cfdd166f8bea9ec42933d7211d30fe
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_main

          create_pull_request: true
          pull_request_title: "New Crowdin translations"
          pull_request_body: "New Crowdin pull request with translations"
          pull_request_base_branch_name: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```
