### DISCUSSION TITLE
Missing documentation about how to pull translation later once translated and more

### DISCUSSION THREAD

**Discussion by dprevost-LMI** [crowdin/github-action#258] [General]
Thanks for your GitHub action plugin and the good documentation that helped us kickstart.

I noted a few missing crucial information so that we could make a complete working solution:
1. What are the basic permissions for uploading and downloading translations in the Crodwin project token? I understand it is specific for each integration, but a basic example of a simple integration should be provided to help us. [This post](https://github.com/crowdin/github-action/issues/230#issuecomment-2160603251) end-up helping me

2. Once we have a working example and the PR gets created, we need to wait for a human to translate the token and pull those later. There are no mentions of possible strategies to tackle that. This is essential documentation to provide. On my part, I use the scheduling approach of Github action Con trask to pull a couple of times per day. I added the below to the on keyword:
```
on:
...
  schedule:
    # Running at 8 AM, 12 PM, 5 PM, and midnight.
    - cron: '0 8,12,17,0 * * *'
```

3. I had to do some twists to correctly create the proper PR from the base branch and all. Below is what I used. That is another helpful thing that would be nice to document

```
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
```
