### DISCUSSION TITLE
Option to create missing sources

### DISCUSSION THREAD

**Discussion by dprevost-LMI** [crowdin/github-action#259] [Q&A]
I'm getting the errors below after my integration, and I would like an option so that the missing sources can be created by themselves. Does such a config already exist?

I might create the empty source file myself as a workaround, but it is a burden. If there is no such config, I might enter a feature request!

```
Due to missing respective sources, the following translations will be omitted
```

![Screenshot 2024-12-09 at 12 23 43 PM](https://github.com/user-attachments/assets/0f05aace-c4de-407a-86cb-9abbe81bf3cd)

**Comment by dprevost-LMI** [comment]
🤔 There is something I'm not sure to understand completely. I created those language files (like `ios.txt.fr`) in my GitHub project. By doing so, I thought it would please the Github action, but it did not.

If anyone can help me, it would be appreciated! Thanks!

**Comment by andrii-bodnar** [comment]
Hi @dprevost-LMI, please share your `crowdin.yml` configuration file and the action configuration.

Looking at the screenshot, there is definitely something weird with the placeholder `%two_letters_code%`. It shouldn't be there. I would suggest to check this first, maybe something is wrong with the `translation` pattern or the "Resulting file after translation export" value in the source file settings in Crowdin.

**Reply by dprevost-LMI** [reply]
Yes, I will share (I do not have access right now); something seems up with that placeholder. At the same time, we already use that placeholder with the Webhook integration, and it works well so it is wierd

**Comment by dprevost-LMI** [comment]
Here you go @andrii-bodnar 

Let me know if it looks like a bug; I will transfer that to the appropriate place!

My crowdin.yml at the root:
```
files:
  - source: /packages/app/i18n/crowdin/all-messages.json
    translation: /packages/app/i18n/crowdin/all-messages_%locale_with_underscore%.json
  - source: /packages/app/i18n/misc/release-notes/202**/*.txt
    translation: /packages/app/i18n/misc/release-notes/202**/%original_file_name%.%two_letters_code%
  - source: /packages/app/i18n/misc/store/*.txt
    translation: /packages/app/i18n/misc/store/%original_file_name%.%two_letters_code%
  - source: /packages/react-native-container/internal_folder/@goto/container/ios/en-US.lproj/InfoPlist.strings
    translation: /packages/react-native-container/internal_folder/@goto/container/ios/%locale%.lproj/InfoPlist.strings
pull_request_title: 'chore: Update Crowdin translations'
pull_request_labels:
  - translations
```

GitHub action:
```
name: Branch Crowdin translations
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened, edited, converted_to_draft, ready_for_review]
    branches: [develop]
    paths:
      - 'packages/app/i18n/crowdin/all-messages.json'
      - 'packages/app/i18n/misc/**/android.txt'
      - 'packages/app/i18n/misc/**/ios.txt'
      - 'packages/react-native-container/internal_folder/@goto/container/ios/en-US.lproj/InfoPlist.strings'
  schedule:
    # Running at 8 AM, 12 PM, 5 PM, and midnight.
    - cron: '0 8,12,17,0 * * *'
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  BRANCH_REF: ${{ github.ref }}
jobs:
  i18n-translations-ready:
    if: github.event.pull_request.draft == false && contains(github.event.pull_request.labels.*.name, 'i18n-translations-ready')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Crowdin translations process
        uses: crowdin/github-action@v2.4.0
        with:
          # Upload token configuration in Crowdin
          upload_sources: true
          upload_translations: true
          download_translations: true
          crowdin_branch_name: ${{ env.BRANCH_NAME }}

          # PR configuration in GitHub
          create_pull_request: true
          localization_branch_name: l10n_${{ env.BRANCH_NAME }}
          skip_ref_checkout: true
          pull_request_title: 'chore: Update Crowdin translations for ${{ env.BRANCH_NAME }}!'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_labels: 'translations'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: '*MASK*'
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_ACCESS_TOKEN }}

```
