### DISCUSSION TITLE
Usage of AI localization with Crowdin branches

### DISCUSSION THREAD

**Discussion by amannn** [crowdin/github-action#280] [Q&A]
Hey @andrii-bodnar, I'm currently trying out the [AI localization workflow](https://github.com/crowdin/github-action/blob/master/docs/AI.md)!

So far, this is working for me, but one issue I see with this workflow is that translations are only generated on a push to `main`. This way, you don't get a preview of translations while working on a feature branch, and if a push to `main` means a deployment, you'll deploy with missing translations while a PR with translations is being added.

So the adjustments I'm trying to make are:
1. Trigger the action on every branch
2. Set `create_pull_request` to `false` and `localization_branch_name` to `${{ github.ref_name }}` to get translations directly on feature branches
3. Set `crowdin_branch_name` to `${{ github.ref_name }}` as well, so translation changes in feature branches don't interfere with production translations

This seems to be generally working for me, but the `crowdin_branch_name` setting seems to set up a Crowdin branch from scratch, therefore AI translation to target locales completely regenerates translations instead of using what's already available in the production translation set.

It seems like [`crowdin branch clone`](https://crowdin.github.io/crowdin-cli/commands/crowdin-branch-clone) is what I'm looking for, but I'm unsure if this can be integrated with the Crowdin GitHub action.

Another aspect to consider is that I want Crowdin branches to be deleted once the branch in my VCS is deleted, I guess that would require another manual step …

Can you provide some guidance here on whether this workflow is possible currently with the Crowdin GitHub action? Or should users be encouraged to use the CLI manually once branches become necessary? The former would definitely be preferred from my perspective.

Many thanks for your help!

<details>
<summary>My current workflow file</summary>

```yml
name: Translations
on:
  push:
    paths: ['messages/**/*.json']
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Upload messages
        uses: crowdin/github-action@v2
        with:
          crowdin_branch_name: ${{ github.ref_name }}
          upload_sources: true
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      - name: AI pre-translate
        uses: crowdin/github-action@v2
        with:
          command: 'pre-translate'
          command_args: '--method ai --ai-prompt=${{ vars.CROWDIN_PROMPT_ID }}'
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      - name: Download translations
        uses: crowdin/github-action@v2
        with:
          crowdin_branch_name: ${{ github.ref_name }}
          upload_sources: false
          download_translations: true
          localization_branch_name: ${{ github.ref_name }}
          create_pull_request: false
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

</details>

**Comment by andrii-bodnar** [comment]
Hi @amannn!

I wanted to make this guide as simple as possible, so pushing to `main` was the simplest way of the trigger :). But there are a lot of possible options documented in the [Triggers](https://github.com/crowdin/github-action/blob/master/docs/EXAMPLES.md#triggers) section.

The described strategy with the `create_pull_request: false` and `localization_branch_name: ${{ github.ref_name }}` seems an ideal setup. It will require separate workflows or jobs for uploading sources and downloading translations. To avoid the Pre-Translation of the strings pushed to the newly created branch in Crowdin, try to adjust the [Duplicate Strings Management](https://support.crowdin.com/project-settings/import/#duplicate-strings-management) settings.

The `crowdin branch clone` command is only for [String-based](https://support.crowdin.com/creating-project/#string-based-project) projects, and I believe it's not needed in this setup, the duplicate strings option should handle everything. 

However, to automatically delete branches from Crowdin, some additional setup is indeed required. In this case, you can use the `crowdin branch delete` CLI command along with the `command` and `command_args` action inputs.

**Reply by amannn** [reply]
Many thanks for the pointers, that definitely helped!

What I ended up with now are these two workflows:

```yml
name: Crowdin translations
on:
  push:
    paths: ['messages/en-US.json']
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Upload sources
        uses: crowdin/github-action@v2
        with:
          crowdin_branch_name: ${{ github.ref_name }}
          upload_sources: true
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      - name: AI pre-translate
        uses: crowdin/github-action@v2
        with:
          command: 'pre-translate'
          command_args: '--method ai --ai-prompt=${{ vars.CROWDIN_PROMPT_ID }} --branch=${{ github.ref_name }}'
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      - name: Download translations
        uses: crowdin/github-action@v2
        with:
          crowdin_branch_name: ${{ github.ref_name }}
          upload_sources: false
          download_translations: true
          localization_branch_name: ${{ github.ref_name }}
          create_pull_request: false
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

```yml
name: Cleanup Crowdin branch

on:
  pull_request:
    types: [closed]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crowdin/github-action@v2
        with:
          command: 'branch delete'
          command_args: '${{ github.head_ref }}'
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

I also switched to "Show within a version branch (strict detection) - duplicates will be hidden only between versions branches".

Do you think that's a setup you'd recommend for such a branch-based workflow?
