### ISSUE TITLE
request: create OAuth to Actions migration guide

### ISSUE THREAD

**Issue by zeke** [crowdin/github-action#11]
My team is currently using Crowdin's OAuth [GitHub integration](https://support.crowdin.com/github-integration/) feature to sync files between our Crowdin project and our GitHub repository.

Because of the high volume of git commits that are created on that integration, we've run into a number of rate limiting issues with our CI and deployment setups. So we are excited there's an Action now and we would love to migrate to it so we can have more control over how (and when) we sync files.

I created a test project to try out the new Action, and with the help of @og-fox and @VBeytok, I was able to get it working: https://github.com/docs/crowdin-action-test/pull/2. 🙌 

I think it would be really helpful to customers if there was a guide for migrating from an existing OAuth setup to an Actions workflow.

A few gotchas come to mind:

- If you're using a `crowdin.yml` file, you'll need to add `preserve_hierarchy: true` to keep the directory structure the same between Crowdin and GitHub (even if you weren't already using this setting in your existing OAuth integration) See https://github.com/crowdin/github-action/issues/7#issuecomment-623151376
- `localization_branch_name` should be set to the existing git branch name you're using for Crowdin PRs. See https://github.com/crowdin/github-action/issues/10
- `crowdin_branch_name` should also be set
- What else?

**Comment by crowdin-support** [comment]
Hi @zeke Seems you've mentioned all the key points but let me double-check with the developers what other things might be important for migration. Will get back to you with the updates soon

**Comment by VBeytok** [comment]
Hi @zeke just done a test migration from an existing OAuth to an Action workflow.
I had the following configuration file:
```yaml
files:
  - source: /**/*.txt
    translation: /**/%two_letters_code%.txt
```
and added credentials:
```yaml
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /**/*.txt
    translation: /**/%two_letters_code%.txt
```

Then created secrets `CROWDIN_PROJECT_ID` and `CROWDIN_PERSONAL_TOKEN` in `project\Settings\ Secrets`

And finally created workflow:
```yaml
name: Crowdin Action

on:
  push:
    branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.0.4
      with:
        upload_translations: true
        download_translations: true
        crowdin_branch_name: 'github_action'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

Structure looks same without `preserve_hierarchy`
![Screenshot 2020-05-05 at 13 53 58](https://user-images.githubusercontent.com/46049489/81058877-066b5900-8ed8-11ea-8d86-970c0247a6d6.png)
