### ISSUE TITLE
Error: Configuration file doesn't exists.

### ISSUE THREAD

**Issue by KhushalGupta** [crowdin/github-action#111]
**Describe the bug**
I have created a crowdin.yml new workflow and crowdin.yml configuration file at a location inside my repo. On running the workflow, I get the error:-
<img width="699" alt="Screen Shot 2022-03-14 at 12 32 34" src="https://user-images.githubusercontent.com/17666396/158163680-29791cc6-134b-487d-b234-2f74421d5d11.png">

**To Reproduce**
1. Crowdin Github Action configuration
```
name: Crowdin Action

on: 
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.4.6
      with:
        upload_translations: true
        download_translations: false
        config: ./{folder-name}/src/main/.../crowdin.yml
      env:
        GITHUB_TOKEN: ${{ token }}
        CROWDIN_PROJECT_ID: ${{ project_id }}
        CROWDIN_PERSONAL_TOKEN: ${{ project_key }}
```
3. `crowdin.yml` file content
```
project_id_env: project_id
api_token_env: personal_token
base_path: "{folder-name}/src/main/.../translations"
preserve_hierarchy: true

files:
  - source: "en.json"
    translation: "en.json"
    dest: "dest.json"
    type: "json"
```
5. Information about workflow (OS, steps, etc.)

**Expected behavior**
It should read the configuration file from this location.

**Screenshots**

**Additional context**
