### ISSUE TITLE
Is pull_request_base_branch_name deprecated?

### ISSUE THREAD

**Issue by taishikato** [crowdin/github-action#113]
**Describe the bug**

I used `pull_request_base_branch_name: "develop"` to make a PR into develop branch automatically.
But GitHub Actions showed me the message below and the PE is always into `main` branch.
```
Warning: Unexpected input(s) 'pull_request_base_branch_name', valid inputs are ['entryPoint', 'args', 'upload_sources', 'upload_translations', 'download_translations', 'language', 'push_translations', 'localization_branch_name', 'create_pull_request', 'crowdin_branch_name', 'identity', 'config', 'dryrun_action', 'project_id', 'token', 'base_url', 'base_path', 'source', 'translation']
```

**To Reproduce**
Crowdin Github Action configuration

```yml
name: Get translation files and make a PR

on:
  pull_request:
    types: [opened]
    branches: [main]

jobs:
  upload-sources-on-crowdin:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'develop' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: crowdin action
        uses: crowdin/github-action@1.0.4
        with:
          config: crowdin.yml
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: incoming-translations
          create_pull_request: true
          pull_request_base_branch_name: "develop"
          crowdin_branch_name: "my-app"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```
**Expected behavior**

A new PR is made and the base branch should be `develop` branch.

Thanks!

**Screenshots**

**Additional context**
