### ISSUE TITLE
crowdin github action fails due to folder permission

### ISSUE THREAD

**Issue by laurentleseigneur** [crowdin/github-action#114]
**Describe the bug**
Hi all, thanks for your action. It seems a change done somewhere may be in Github runner make my action fails due to `to `fatal: unsafe repository ('/github/workspace' is owned by someone else)`

this job was working until yesterday

**To Reproduce**

action is configured with
```
    - name: Crowdin sync
      uses: crowdin/github-action@1.4.7
      with:
        upload_sources: true
        upload_translations: true
        download_translations: true
        localization_branch_name: 'l10n_main'
        create_pull_request: true
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

 
```
my action log is 
```
Run crowdin/github-action@1.4.7
/usr/bin/docker run --name bcf090af149a5ed5c4402b5b32f[26](https://github.com/bonitasoft-presales/presales-localization/runs/6002923363?check_suite_focus=true#step:4:26)78004ace_baa940 --label 2bcf09 --workdir /github/workspace --rm -e GITHUB_TOKEN -e CROWDIN_PROJECT_ID -e CROWDIN_PERSONAL_TOKEN -e INPUT_UPLOAD_SOURCES -e INPUT_UPLOAD_TRANSLATIONS -e INPUT_DOWNLOAD_TRANSLATIONS -e INPUT_LOCALIZATION_BRANCH_NAME -e INPUT_CREATE_PULL_REQUEST -e INPUT_PROJECT_ID -e INPUT_TOKEN -e INPUT_UPLOAD_SOURCES_ARGS -e INPUT_UPLOAD_LANGUAGE -e INPUT_AUTO_APPROVE_IMPORTED -e INPUT_IMPORT_EQ_SUGGESTIONS -e INPUT_UPLOAD_TRANSLATIONS_ARGS -e INPUT_DOWNLOAD_LANGUAGE -e INPUT_SKIP_UNTRANSLATED_STRINGS -e INPUT_SKIP_UNTRANSLATED_FILES -e INPUT_EXPORT_ONLY_APPROVED -e INPUT_PUSH_TRANSLATIONS -e INPUT_COMMIT_MESSAGE -e INPUT_PULL_REQUEST_TITLE -e INPUT_PULL_REQUEST_BODY -e INPUT_PULL_REQUEST_LABELS -e INPUT_PULL_REQUEST_BASE_BRANCH_NAME -e INPUT_DOWNLOAD_TRANSLATIONS_ARGS -e INPUT_ADD_CROWDIN_BRANCH -e INPUT_NEW_BRANCH_TITLE -e INPUT_NEW_BRANCH_EXPORT_PATTERN -e INPUT_NEW_BRANCH_PRIORITY -e INPUT_DELETE_CROWDIN_BRANCH -e INPUT_CROWDIN_BRANCH_NAME -e INPUT_IDENTITY -e INPUT_CONFIG -e INPUT_DRYRUN_ACTION -e INPUT_GITHUB_BASE_URL -e INPUT_GITHUB_API_BASE_URL -e INPUT_GITHUB_USER_NAME -e INPUT_GITHUB_USER_EMAIL -e INPUT_GPG_PRIVATE_KEY -e INPUT_BASE_URL -e INPUT_BASE_PATH -e INPUT_SOURCE -e INPUT_TRANSLATION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/presales-localization/presales-localization":"/github/workspace" 2bcf09:0af149a5ed5c4402b5b[32](https://github.com/bonitasoft-presales/presales-localization/runs/6002923363?check_suite_focus=true#step:4:32)f2678004ace
STARTING CROWDIN ACTION
UPLOAD SOURCES
✔️  Fetching project info
✔️  File 'app-Ticketing/localization.json'
✔️  File 'app-HRManagement/localization.json'
✔️  File 'showroom-cloud/localization.json'
✔️  File 'app-InvoiceManagement/localization.json'
UPLOAD TRANSLATIONS
✔️  Fetching project info
✔️  Translation file 'app-HRManagement/localization_es-ES_crowdin.json' has been uploaded
✔️  Translation file 'app-Ticketing/localization_fr-FR_crowdin.json' has been uploaded
✔️  Translation file 'showroom-cloud/localization_es-ES_crowdin.json' has been uploaded
✔️  Translation file 'app-Ticketing/localization_es-ES_crowdin.json' has been uploaded
✔️  Translation file 'app-InvoiceManagement/localization_es-ES_crowdin.json' has been uploaded
✔️  Translation file 'app-HRManagement/localization_fr-FR_crowdin.json' has been uploaded
✔️  Translation file 'app-InvoiceManagement/localization_fr-FR_crowdin.json' has been uploaded
✔️  Translation file 'showroom-cloud/localization_fr-FR_crowdin.json' has been uploaded
DOWNLOAD TRANSLATIONS
✔️  Fetching project info
✔️  Building ZIP archive with the latest translations
✔️  Building translation (100%)
✔️  Downloading translations
✔️  Extracting archive
✔️  Extracted: 'app-HRManagement/localization_es-ES_crowdin.json'
✔️  Extracted: 'app-HRManagement/localization_fr-FR_crowdin.json'
✔️  Extracted: 'app-InvoiceManagement/localization_es-ES_crowdin.json'
✔️  Extracted: 'app-InvoiceManagement/localization_fr-FR_crowdin.json'
✔️  Extracted: 'app-Ticketing/localization_es-ES_crowdin.json'
✔️  Extracted: 'app-Ticketing/localization_fr-FR_crowdin.json'
✔️  Extracted: 'showroom-cloud/localization_es-ES_crowdin.json'
✔️  Extracted: 'showroom-cloud/localization_fr-FR_crowdin.json'
CONFIGURATION GIT USER
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```
