### ISSUE TITLE
Possible regression - Check the source paths in your configuration file

### ISSUE THREAD

**Issue by kalilistic** [crowdin/github-action#122]
**Describe the bug**
This workflow/configuration used to upload sources and download translations as expected for several months. Earlier this year (first case noticed on 4/18) - I started receiving an error that source was not found. This happened with version 1.1.0. I upgraded to 1.4.9 and still had the error. I then downgraded to 1.0.4 and the issue was resolved (although not ideal).

STARTING CROWDIN ACTION
UPLOAD SOURCES
✔️  Fetching project info
❌ No sources found for 'src/SillyChat/SillyChat/Resource/source/SillyChat_Localizable.json' pattern. Check the source paths in your configuration file
❌ Current execution finished with errors

**To Reproduce**
Use the following config/workflow file.

_Config File_
```
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: false
files:
  - source: src/SillyChat/SillyChat/Resource/source/SillyChat_Localizable.json
    translation: src/SillyChat/SillyChat/Resource/translation/%two_letters_code%.json
```

_Workflow File_
```
name: Update localization

on:
  workflow_dispatch:
  
jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Update localization
      uses: crowdin/github-action@1.0.4
      with:
          upload_sources: true
          upload_translations: true
          auto_approve_imported: true
          import_eq_suggestions: true
          download_translations: true
          skip_untranslated_strings: true
          export_only_approved: true
          push_translations: true
          commit_message: 'Update localization'
          create_pull_request: true
          pull_request_title: 'Update localization'
          pull_request_body: 'Update localization with latest translations from crowdin'
          config: '.github/crowdin.yml'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        CROWDIN_PROJECT_ID: ${{secrets.CROWDIN_PROJECT_ID}}
        CROWDIN_PERSONAL_TOKEN: ${{secrets.CROWDIN_PERSONAL_TOKEN}}
```

**Expected behavior**
Crowdin action uploads source file as expected.

**Screenshots**
N/A

**Additional context**
N/A
