### ISSUE TITLE
Commit signing no longer working since 1.4.9

### ISSUE THREAD

**Issue by sbrandwoo** [crowdin/github-action#126]
**Describe the bug**

There was [a change](https://github.com/crowdin/github-action/commit/ecd7eb0ef6f3cfa16293c79e9cbc4bc5b5fd9c49) to how signed commits work in 1.4.9, which means our commits are no longer being signed.

**To Reproduce**

We have config as follows:

```yaml
      - name: crowdin action
        uses: crowdin/github-action@1.4.9
        with:
          // ... other config
          gpg_private_key: ${{ secrets.GPG_SIGN_KEY }}
          github_user_email: '<OUR EMAIL>'
```
We are not setting `gpg_passphrase` as we don't have a passphrase.

PRs are opened correctly with the correct commits, but the commits are not signed.

**Expected behavior**
Commits to PRs should be signed.

**Additional context**
Looking at the change that caused the issue, is `gpg_passphrase` now a required field? Should it instead be optional?

This seems to be a breaking change and shouldn't have been released as a patch version update?
