### ISSUE TITLE
Error using the 'upload sources' to upload a single file with no config

### ISSUE THREAD

**Issue by jasonleenaylor** [crowdin/github-action#127]
When using the Github action to upload a single source file I receive an error: 
"No sources found for 'home/runner/work/libpalaso/libpalaso/Palaso.en.xlf' pattern. Check the source paths in your configuration file"

**To Reproduce**
This is the relevant part of our github action. I've verified that the file exists where the action expects it to be and that the -t argument matches the pattern in 'Resulting file after translations export:'

```
    - name: Upload Source Strings To Crowdin
      uses: crowdin/github-action@ecd7eb0ef6f3cfa16293c79e9cbc4bc5b5fd9c49
      with:
        upload_sources: true
        upload_sources_args: '-s /home/runner/work/libpalaso/libpalaso/Palaso.en.xlf -t /%local%/Palaso.%locale%.xlf -T ${{ secrets.CROWDIN_ACCESS_TOKEN }} -i ${{ secrets.CROWDIN_PROJECT_ID }}'
        push_translations: false
        create_pull_request: false
```

I expected the action to upload the file. I can see that the version 2 API is being used by the action, but it fails to upload the updated source file.
