### ISSUE TITLE
Using `gpg_passphrase` triggers warning.

### ISSUE THREAD

**Issue by ottosuess** [crowdin/github-action#132]
**Describe the bug**

When running the crowdin github action with the new `gpg_passphrase` option it displays a warning:

![image](https://user-images.githubusercontent.com/37940680/176416271-58512b80-6621-4e37-92a0-0fc1730141da.png)

`Unexpected input(s) 'gpg_passphrase', valid inputs are ['entryPoint', 'args', 'upload_sources', 'upload_sources_args', 'upload_translations', 'upload_language', 'auto_approve_imported', 'import_eq_suggestions', 'upload_translations_args', 'download_translations', 'download_language', 'skip_untranslated_strings', 'skip_untranslated_files', 'export_only_approved', 'push_translations', 'commit_message', 'localization_branch_name', 'create_pull_request', 'pull_request_title', 'pull_request_body', 'pull_request_labels', 'pull_request_base_branch_name', 'download_translations_args', 'add_crowdin_branch', 'new_branch_title', 'new_branch_export_pattern', 'new_branch_priority', 'delete_crowdin_branch', 'crowdin_branch_name', 'identity', 'config', 'dryrun_action', 'github_base_url', 'github_api_base_url', 'github_user_name', 'github_user_email', 'gpg_private_key', 'project_id', 'token', 'base_url', 'base_path', 'source', 'translation']`

I believe that option has to be added to `action.yml`.

**To Reproduce**

github workflow:

```yaml
    - name: Create Crowdin PR
      uses: crowdin/github-action@1.4.9
      with:
        ...
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
```
