### ISSUE TITLE
delete_crowdin_branch fails if branch name contains a space

### ISSUE THREAD

**Issue by weakfl** [crowdin/github-action#133]
**Describe the bug**

Trying to cleanup orphaned crowdin branches when PRs are merged/closed, but it fails if the branch name contains a space:

```
STARTING CROWDIN ACTION
REMOVING BRANCH [prefix] feature.foobar
Unmatched argument at index 3: 'feature.foobar'
SYNOPSIS:
crowdin branch delete <name> [CONFIG OPTIONS] [OPTIONS]

[...]
```

**To Reproduce**

A workflow like:

```yaml
      - name: crowdin action
        uses: crowdin/github-action@1.4.9
        with:
          upload_sources: false
          create_pull_request: false
          download_translations: false
          push_translations: false
          delete_crowdin_branch: "[prefix] foobar"
```

**Expected behavior**

Delete the crowdin branch.
