### ISSUE TITLE
`api_token` & `project_id` are missing in the configuration file

### ISSUE THREAD

**Issue by Baptiste-Taho** [crowdin/github-action#137]
**Describe the bug**
The action is raising this error:
```
❌ Configuration file is invalid. Check the following parameters in your configuration file:
	- Required option 'api_token' is missing
	- Required option 'project_id' is missing
```

**To Reproduce**
1. Crowdin Github Action configuration
```yml
jobs:
  build-gettext-and-crowdin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
     ... more unrelated steps

      - name: crowdin action
        uses: crowdin/github-action@1.4.12
        with:
          upload_translations: true
          download_translations: false
          config: crowdin.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

2. `crowdin.yml` file content
```yml
"project_id_env" : CROWDIN_PROJECT_ID
"api_token_env" : CROWDIN_PERSONAL_TOKEN

"base_path" : "."
"base_url" : "https://api.crowdin.com"
"preserve_hierarchy": true

"files" : [
  {
    "source" : "/translations/messages.pot",
    "translation" : "/translations/%two_letters_code%/LC_MESSAGES/messages.po",
    "languages_mapping" : {
      "two_letters_code" : {
        "fr" : "fr",
      }
    }
  }
]
```

4. Information about workflow (OS, steps, etc.)
OS: unbuntu-latest
Steps: Checkout, then python 3.9 setup (+ dependencies), then Extracting gettext files, and commit
The Crowdin action goes after all these steps

**Expected behavior**
Uploading my files to Crowdin, using the TOKEN & ID stored in my secrets.

**Screenshots**
![image](https://user-images.githubusercontent.com/61520798/184870966-ad47b955-ef3d-468b-8ec8-07d574efef11.png)

**Additional context**
I had first a configuration with the `project_id` hard coded, and the `api_token` with a Github secret, it wasn't raising this error but it said that the `api_token` was bad. So, after reading #7 I moved to `project_id_env` and `api_token_env` thinking it made better use of Github Actions variables.
