### ISSUE TITLE
Option to commit directly to target branch

### ISSUE THREAD

**Issue by RDIL** [crowdin/github-action#150]
**Is your feature request related to a problem? Please describe.**

Having the action constantly create PRs is annoying.  I want to be able to run a cron task (the cron part would be handled by actions itself, not this action) that just directly commits translation updates, instead of creating a PR.

Sure, I could create an auto-merge workflow, but that still would send out emails, which is just annoying.

**Describe the solution you'd like**

An option to commit new changes directly to the target branch.

**Describe alternatives you've considered**

Auto-merge PR workflow - see above.

**Comment by DimaYashchyshyn** [comment]
Hi @RDIL 
Thanks for the idea, we'll consider whether it's possible to implement it.

**Comment by andrii-bodnar** [comment]
Hi @RDIL,

please try specifying the step configuration:

```yaml
- name: crowdin action
   uses: crowdin/github-action@1.5.1
   with:
     upload_sources: true
     download_translations: true
     push_translations: true
     commit_message: 'New Crowdin translations by Github Action'
     localization_branch_name: main
     create_pull_request: false
```
