### ISSUE TITLE
never downloads translations

### ISSUE THREAD

**Issue by Geczy** [crowdin/github-action#162]
**Describe the bug**

Anything you can do to check? Project is https://crowdin.com/project/dotabod

https://github.com/dotabod/backend/actions/runs/4050330924/jobs/6967618544

```
STARTING CROWDIN ACTION
DOWNLOAD TRANSLATIONS
✔️  Fetching project info
✔️  Building ZIP archive with the latest translations
✔️  Building translation (100%)
✔️  Downloading translations
✔️  Extracting archive
⚠️  Couldn't find any file to download
⚠️  Downloaded translations don't match the current project configuration. The translations for the following sources will be omitted (use --verbose to get the list of the omitted translations):
	- twitch-chat-listener/locales/en/translation.json (9)
	- web/locales/en/translation.json (9)
	- twitch-eventsub-listener/locales/en/translation.json (9)
```

**Comment by andrii-bodnar** [comment]
@Geczy please try the following configuration for the `crowdin-download.yml` workflow:

```yml
- name: Download Crowdin Translations
  uses: crowdin/github-action@v1
  with:
    download_translations: true
    upload_sources: false
    upload_translations: false
    create_pull_request: false
    push_translations: false
  env:
    CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
    CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```
