### ISSUE TITLE
Downloaded source file is in wrong directory.

### ISSUE THREAD

**Issue by adrianbuskiewicz** [crowdin/github-action#166]
**Describe the bug**
New "download sources" feature doesn't put source file in source path but to root directory of GitHub repository.

**To Reproduce**
1. Using action to create PR to download translation and download sources to GH repository.
2. Translations are downloaded as expected (to path in "translations:") but source file is downloaded to root directory of repository not to path specified in "source:".

**Expected behavior**
File is downloaded in same location as is specified in "source:".

**Additional context**
Do I need to specify something else to work it as expected?

**Comment by andrii-bodnar** [comment]
Hi @adrianbuskiewicz, please provide the workflows example and your `crowdin.yml` configuration file (without credentials)

**Comment by adrianbuskiewicz** [comment]
```
download-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update repo with translations
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          download_sources: true
          create_pull_request: true
          pull_request_title: 'New Crowdin translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_base_branch_name: 'master'
          source: 'locale/en/LC_MESSAGES/django.po'
          translation: 'locale/%two_letters_code%/LC_MESSAGES/%original_file_name%'
```
