### ISSUE TITLE
Download doesn't respect %locale%

### ISSUE THREAD

**Issue by Geczy** [crowdin/github-action#170]
**Describe the bug**
The download doesn't attempt to go into %locale%, it instead keeps showing two letter code no matter what

**To Reproduce**

 **Expected behavior**
Because I have `%locale%` defined, I'm expecting uk to download to uk-UA (also because i have the mapping set!) but the output keeps downloading to uk

I also have brazillian portuguese and it keeps downloading to `pt` not `pt-BR` and i do not see why

Project folder is here https://github.com/dotabod/backend/tree/master/packages/dota/locales

```yml
      - name: Download Crowdin Translations
        uses: crowdin/github-action@v1
        with:
          download_translations: true
          upload_sources: false
          upload_translations: false
          create_pull_request: false
          push_translations: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

```yml
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: /packages/dota/locales/en/*.json
    translation: /packages/dota/locales/%locale%/%original_file_name%
    type: i18next_json
    languages_mapping:
      locale:
        "en-US": "en"
        "es-ES": "es"
        "uk": "uk-UA"
  - source: /packages/twitch/**/locales/en/*.json
    translation: /packages/twitch/**/locales/%locale%/%original_file_name%
    type: i18next_json
    languages_mapping:
      locale:
        "en-US": "en"
        "es-ES": "es"
        "uk": "uk-UA"
```

Anything you can do to check? Project is [crowdin.com/project/dotabod](https://crowdin.com/project/dotabod)

```bash
$ just i18nd
Downloading translations
'c:/Program Files (x86)/CrowdinCLI/crowdin.bat' download --config './crowdin.yml' --verbose
[OK] Fetching project info 
[OK] Building ZIP archive with the latest translations
[OK] Building translation (100%)
[OK] Downloading translations 
[OK] Extracting archive 
[OK] Extracted: 'packages\dota\locales\es\translation.json'
[OK] Extracted: 'packages\dota\locales\pt\translation.json'
[OK] Extracted: 'packages\twitch\chat\locales\es\translation.json'
[OK] Extracted: 'packages\twitch\chat\locales\pt\translation.json'
[OK] Extracted: 'packages\twitch\events\locales\es\translation.json'
[OK] Extracted: 'packages\twitch\events\locales\pt\translation.json'
[WARNING] Downloaded translations don't match the current project configuration. The translations for the following sources will be omitted (use --verbose to get the list of the omitted translations):
        - dota\locales\en\translation.json (26)
                - packages\dota\locales\af\translation.json
                - packages\dota\locales\ar\translation.json
                - packages\dota\locales\ca\translation.json
                - packages\dota\locales\cs\translation.json
                - packages\dota\locales\da\translation.json
                - packages\dota\locales\de\translation.json
                - packages\dota\locales\el\translation.json
                - packages\dota\locales\fa\translation.json
                - packages\dota\locales\fi\translation.json
                - packages\dota\locales\fr\translation.json
                - packages\dota\locales\he\translation.json
                - packages\dota\locales\hu\translation.json
                - packages\dota\locales\it\translation.json
                - packages\dota\locales\ja\translation.json
                - packages\dota\locales\ko\translation.json
                - packages\dota\locales\nl\translation.json
                - packages\dota\locales\no\translation.json
                - packages\dota\locales\pl\translation.json
                - packages\dota\locales\ro\translation.json
                - packages\dota\locales\ru\translation.json
                - packages\dota\locales\sr\translation.json
                - packages\dota\locales\sv\translation.json
                - packages\dota\locales\tr\translation.json
                - packages\dota\locales\uk\translation.json
                - packages\dota\locales\vi\translation.json
                - packages\dota\locales\zh\translation.json
        - twitch\events\locales\en\translation.json (26)
                - packages\twitch\events\locales\af\translation.json
                - packages\twitch\events\locales\ar\translation.json
                - packages\twitch\events\locales\ca\translation.json
                - packages\twitch\events\locales\cs\translation.json
                - packages\twitch\events\locales\da\translation.json
                - packages\twitch\events\locales\de\translation.json
                - packages\twitch\events\locales\el\translation.json
                - packages\twitch\events\locales\fa\translation.json
                - packages\twitch\events\locales\fi\translation.json
                - packages\twitch\events\locales\fr\translation.json
                - packages\twitch\events\locales\he\translation.json
                - packages\twitch\events\locales\hu\translation.json
                - packages\twitch\events\locales\it\translation.json
                - packages\twitch\events\locales\ja\translation.json
                - packages\twitch\events\locales\ko\translation.json
                - packages\twitch\events\locales\nl\translation.json
                - packages\twitch\events\locales\no\translation.json
                - packages\twitch\events\locales\pl\translation.json
                - packages\twitch\events\locales\ro\translation.json
                - packages\twitch\events\locales\ru\translation.json
                - packages\twitch\events\locales\sr\translation.json
                - packages\twitch\events\locales\sv\translation.json
                - packages\twitch\events\locales\tr\translation.json
                - packages\twitch\events\locales\uk\translation.json
                - packages\twitch\events\locales\vi\translation.json
                - packages\twitch\events\locales\zh\translation.json
        - twitch\chat\locales\en\translation.json (26)
                - packages\twitch\chat\locales\af\translation.json
                - packages\twitch\chat\locales\ar\translation.json
                - packages\twitch\chat\locales\ca\translation.json
                - packages\twitch\chat\locales\cs\translation.json
                - packages\twitch\chat\locales\da\translation.json
                - packages\twitch\chat\locales\de\translation.json
                - packages\twitch\chat\locales\el\translation.json
                - packages\twitch\chat\locales\fa\translation.json
                - packages\twitch\chat\locales\fi\translation.json
                - packages\twitch\chat\locales\fr\translation.json
                - packages\twitch\chat\locales\he\translation.json
                - packages\twitch\chat\locales\hu\translation.json
                - packages\twitch\chat\locales\it\translation.json
                - packages\twitch\chat\locales\ja\translation.json
                - packages\twitch\chat\locales\ko\translation.json
                - packages\twitch\chat\locales\nl\translation.json
                - packages\twitch\chat\locales\no\translation.json
                - packages\twitch\chat\locales\pl\translation.json
                - packages\twitch\chat\locales\ro\translation.json
                - packages\twitch\chat\locales\ru\translation.json
                - packages\twitch\chat\locales\sr\translation.json
                - packages\twitch\chat\locales\sv\translation.json
                - packages\twitch\chat\locales\tr\translation.json
                - packages\twitch\chat\locales\uk\translation.json
                - packages\twitch\chat\locales\vi\translation.json
                - packages\twitch\chat\locales\zh\translation.json
```
