### ISSUE TITLE
URLs for GitHub Enterprise Seem Unset

### ISSUE THREAD

**Issue by es0329** [crowdin/github-action#173]
Actions appears to successfully upload sources and download translations, before failing GitHub Enterprise authentication while attempting to create its pull request.

**To Reproduce**
1. Action configuration with Enterprise values for `github_base_url` and `github_api_base_url`.
```yml
name: Localization

on:
  push:
    branches: [ "develop" ]
    paths: [
      "presentation/src/main/res/values/strings.xml",
      "presentation/src/main/res/values/plurals.xml",
    ]
permissions: write-all
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  sync-crowdin:
    runs-on: [ self-hosted, docker ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync Translations
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: crowdin-l10n
          skip_untranslated_strings: true
          create_pull_request: true
          pull_request_title: 'Sync Localizations'
          pull_request_body: 'New translations by [Crowdin GitHub Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: "${{ env.BRANCH_NAME }}"
          github_base_url: git.i.XXX.com
          github_api_base_url: git.i.XXX.com/api/v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_SSL_NO_VERIFY: true
          CROWDIN_PROJECT_ID: "${{ secrets.CROWDIN_PROJECT_ID }}"
          CROWDIN_API_TOKEN: "${{ secrets.CROWDIN_API_TOKEN }}"
```
2. Crowdin Configuration
```yml
"project_id_env": CROWDIN_PROJECT_ID
"api_token_env": CROWDIN_API_TOKEN
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
"files": [
  {
    "content_segmentation": 0,
    "first_line_contains_header": true,
    "translate_attributes": 0,
    "source": "presentation/src/main/res/values/strings.xml",
    "translation": "presentation/src/main/res/values-%android_code%/strings.xml",
    "translation_replace": {
        "ja-rJP": "ja",
        "zh-TW": "zh-rTW"
    }
  },
  {
    "content_segmentation": 0,
    "first_line_contains_header": true,
    "translate_attributes": 0,
    "source": "presentation/src/main/res/values/plurals.xml",
    "translation": "presentation/src/main/res/values-%android_code%/plurals.xml",
    "translation_replace": {
        "ja-rJP": "ja",
        "zh-TW": "zh-rTW"
    }
  }
]
```

**Expected behavior**
Successful upload, download, and pull request.

**Additional context**
Redacted failure output where:
- `ENTERPRISE_URL` logs our enterprise url
- `PUBLIC_URL` logs `github.com` where _I think_ I'd expect to see `ENTERPRISE_URL`
```txt
  PUSH TO BRANCH crowdin-l10n
  [251](ENTERPRISE_URL/runs/12253?check_suite_focus=true#step:4:252)
  [crowdin-l10n 17f5682] New Crowdin translations by GitHub Action
  [252](ENTERPRISE_URL/runs/12253?check_suite_focus=true#step:4:253)
  2 files changed, 34 insertions(+), 49 deletions(-)
  [253](ENTERPRISE_URL/runs/12253?check_suite_focus=true#step:4:254)
  + git push --no-verify --force ***PUBLIC_URL.git
  [254](ENTERPRISE_URL/runs/12253?check_suite_focus=true#step:4:255)
remote: Invalid username or password.
  [255](ENTERPRISE_URL/runs/12253?check_suite_focus=true#step:4:256)
fatal: Authentication failed for 'PUBLIC_URL.git/'
```

Let me know if we've overlooked something. Thank you for any insight.
