### ISSUE TITLE
pull requests are not being created

### ISSUE THREAD

**Issue by moodysalem** [crowdin/github-action#182]
**Describe the bug**
My setup is not creating pull requests after it pushes to the branch

```yaml
permissions:
  contents: write
  pull-requests: write
```

```yaml
      - name: Download from Crowdin
        uses: crowdin/github-action@v1
        with:
          download_translations: true
          commit_message: "synced i18n translations from crowdin"
          localization_branch_name: i18n-translations
          create_pull_request: true
          pull_request_title: New Crowdin Translations
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: main
          source: "src/locales/en.po"
          translation: "src/locales/%two_letters_code%.po"

          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**
Creates a pull request as described

**Additional context**

Here are the relevant logs from the action:
```
Your branch is up to date with 'origin/main'.
Switched to a new branch 'i18n-translations'
PUSH TO BRANCH i18n-translations
[i18n-translations d97bf48] synced i18n translations from crowdin
 27 files changed, 378 insertions(+), 270 deletions(-)
remote: 
remote: Create a pull request for 'i18n-translations' on GitHub by visiting:        
remote:      https://github.com/EkuboProtocol/interface/pull/new/i18n-translations        
remote: 
To https://github.com/EkuboProtocol/interface.git
 * [new branch]      i18n-translations -> i18n-translations
CHECK IF ISSET SAME PULL REQUEST
CREATE PULL REQUEST
PULL REQUEST CREATED: null
```

**Comment by andrii-bodnar** [comment]
Also, please try to explicitly allow GitHub Actions to create pull requests. This setting can be found in a repository's settings under Actions > General > Workflow permissions.

For repositories belonging to an organization, this setting can be managed by admins in organization settings under Actions > General > Workflow permissions.

**Comment by andrii-bodnar** [comment]
It's interesting that this option is disabled. Is there a tooltip with the reason for disabling it?

**Comment by moodysalem** [comment]
Unfortunately no

**Comment by moodysalem** [comment]
> This is probably the reason why the action cannot create a PR. Please try using an alternative action [create-pull-request](https://github.com/marketplace/actions/create-pull-request) to see if it can create a PR

It's failing but I don't think for the same reason

```yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: New Crowdin Translations
          body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: i18n-translations
```
```
Create or update the pull request branch
  /usr/bin/git symbolic-ref HEAD --short
  i18n-translations
  Working base is branch 'i18n-translations'
  /usr/bin/git checkout --progress -B 15146006-d319-[41](https://github.com/EkuboProtocol/interface/actions/runs/5660283434/job/15335656860#step:5:47)3f-93c0-4877fb1602b5 HEAD --
  Switched to a new branch '15146006-d319-413f-93c0-4877fb1602b5'
  /usr/bin/git status --porcelain -unormal --
  /usr/bin/git diff --quiet --
  /usr/bin/git diff --quiet --staged --
  /usr/bin/git stash push --include-untracked
  No local changes to save
  Resetting working base branch 'i18n-translations'
  /usr/bin/git checkout --progress i18n-translations --
  Switched to branch 'i18n-translations'
  /usr/bin/git reset --hard origin/i18n-translations
  fatal: ambiguous argument 'origin/i18n-translations': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
  Error: The process '/usr/bin/git' failed with exit code 128
```
