### ISSUE TITLE
For input string: "***"

### ISSUE THREAD

**Issue by GencBlakqoriP9** [crowdin/github-action#19]
Hello guys,
Thanks a lot for the awesome tool. I'm excited to use it in my build plans.
I tried to use it, but ran into an issue. Here is my setup:

```
    - name: Crowdin action
      uses: crowdin/github-action@1.0.6
      with:
        upload_translations: true
        download_translations: false
        config: ./crowdin.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_API_KEY }}
```
My crowdin.yaml:
```
"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path" : "dist/my_project/assets/i18n/my_project"
"preserve_hierarchy": true

"files": [
  {
    "source" : "en.translations.bundle.json",
    "translation" : "%two_letters_code%.translations.bundle.json",
    "dest" : "my_project.json",
    "type" : "json",
  }
]
```
And this is the result I'm getting:

![image](https://user-images.githubusercontent.com/64162761/83192557-01e03c00-a136-11ea-871f-aaf8b03d180f.png)

Thanks for the help in advance. Take care!
