### ISSUE TITLE
Downloaded .strings files randomly have an empty line at the top.

### ISSUE THREAD

**Issue by CraigSiemens** [crowdin/github-action#198]
**Describe the bug**
When downloading translations, it randomly seems to add an extra empty line at the top of a translated `.strings` file. Often there are no other changes in the file and crowdin shows the file as fully translated. Also, it only seems to affect one file at a time, but can vary which file it affects.

**To Reproduce**
1. Crowdin GitHub Action configuration
```
      - name: Pull translations from Crowdin
        uses: crowdin/github-action@v1.13.1
        with:
            upload_sources: false
            upload_translations: false
            download_translations: true
            skip_untranslated_strings: true
            create_pull_request: false
            push_translations: false
            crowdin_branch_name: ${{ inputs.crowdin_branch }}
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

2. `crowdin.yml` file content
```
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /Modules/**/Sources/Resources/en.lproj/*
    translation: /Modules/**/Sources/Resources/%two_letters_code%.lproj/%original_file_name%
```

3. Information about workflow (OS, steps, etc.)
Our workflow does the following
- checkout or create a branch for the translations
- run the crownin action above to download the translations
- if there are new translations, commit the change and open a PR if needed.

Our project is an iOS app that uses `.strings` files. Our app is broken up into multiple modules, each with it's own strings file.

**Expected behavior**
It shouldn't add blank lines to the start of a file.

**Screenshots**
Here's an example of the change being applied a file.
<img width="1280" alt="Padded Screenshot 2023-09-29 at 12 12 25 PM" src="https://github.com/crowdin/github-action/assets/680442/e7b528bc-0fc2-49f1-ba51-f3e1eac07c86">

**Additional context**
It was occurring to our project a couple months ago. We tried updating to the latest version of the action but it didn't change the behaviour. After a couple days the issue went away and it stopped adding empty lines to the start of files. Within the last week it started occurring again.
