### ISSUE TITLE
.env file at root of source branch breaks action

### ISSUE THREAD

**Issue by shamoon** [crowdin/github-action#210]
**Describe the bug**
We just got this action setup and it seems to work great except for this snag. Apologies if I missed any previous issues / docs about this, I tried searching without success.

Our repo contains a '.env' file at the root and it seems the action tries to parse that, in our case failing and throwing the error `Malformed entry export PROMPT="(pipenv-projectname)$P$G"`

I tried adding e.g. the following and the action succeeds but this causes the PR to include deleting the file, of course
```yaml
    - name: Remove .env
      run: |
        rm -f \
          .env
```

**To Reproduce**
1. Crowdin GitHub Action configuration
```
name: Crowdin Action

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
  push:
    paths: [
      'src/locale/**',
      'src-ui/src/locale/**'
    ]
    branches: [ dev ]

jobs:
  synchronize-with-crowdin:
    name: Crowdin Sync
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: crowdin action
      uses: crowdin/github-action@v1
      with:
        upload_translations: false
        download_translations: true
        crowdin_branch_name: 'dev'
        localization_branch_name: l10n_dev
        pull_request_labels: 'skip-changelog, translation'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

```
2. `crowdin.yml` file content
```yaml
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /src/locale/en_US/LC_MESSAGES/django.po
    translation: /src/locale/%locale_with_underscore%/LC_MESSAGES/django.po
  - source: /src-ui/messages.xlf
    translation: /src-ui/src/locale/messages.%locale_with_underscore%.xlf
```
3. Information about workflow (OS, steps, etc.)
I imagine all thats required is to have a .env in the root of the branch getting checked out

**Expected behavior**
Action success / a way to ignore a .env file

Thanks so much for the action and any support
