### ISSUE TITLE
Return a boolean value if any translations got changed

### ISSUE THREAD

**Issue by mittalyashu** [crowdin/github-action#218]
**Is your feature request related to a problem? Please describe.**

After the Crowdin action is executed we push the updated i18n files to remote bucket. It would be helpful to know if there was any translations got changed from Crowdin.

**Describe the solution you'd like**

Make the Boolean value accessible inside the GitHub action.

**Comment by andrii-bodnar** [comment]
As a workaround, I would suggest the following workflow:

```yml
name: 'Sync with Crowdin'

on:
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: crowdin/github-action@v1
        with:
          upload_sources: true
          download_translations: true
          upload_translations: false
          push_translations: false
          create_pull_request: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: check if there are uncommitted changes and set the result to output
        id: git-status
        run: echo "HAS_CHANGES=$(if git status --porcelain | grep -q .; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT

      - name: Commit and push
        if: steps.git-status.outputs.HAS_CHANGES == 'true'
        run: echo "commit and push"

```
