### ISSUE TITLE
Crowdin GHA failed with pre-translate command

### ISSUE THREAD

**Issue by aprokofjev-mwb** [crowdin/github-action#219]
**Describe the bug**

Crowdin GHA failed with pre-translate command:

```
STARTING CROWDIN ACTION
RUNNING COMMAND crowdin pre-translate -v --method tm -b MB5 --translate-with-perfect-match-only --auto-approve-option=perfect-match-only --translate-untranslated-only 
 Fetching project info 

❌ Couldn't find any files to Pre-Translate in the current project
```

**To Reproduce**

1. workflow step:
```
     - name: Pre-translate via Translation Memory
        uses: crowdin/github-action@v1
        with:
          config: 'app/crowdin.yml'
          command: 'pre-translate'
          command_args: '-v --method tm -b MB5 --translate-with-perfect-match-only --auto-approve-option=perfect-match-only --translate-untranslated-only'
        env:
          HYDRA_CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          HYDRA_CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
```

2. `crowdin.yml` file content:

```
"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files: [
  {
    "source": "/src/main/res/values/strings.xml",
    "translation": "/src/main/res/values-%android_code%/%original_file_name%",
    "type": "android"
  },
]

"escape_quotes": 2
```

**Expected behavior**
GHA shouldn't fail.

**Screenshots**
![Screenshot 2024-02-29 at 3 09 50 PM](https://github.com/crowdin/github-action/assets/101316668/cf64955f-ed1b-4556-98a9-50fad25a2076)

**Additional context**
It works as expected if the same command called from console:

`crowdin pre-translate -v --method tm -b MB5 --translate-with-perfect-match-only --auto-approve-option=perfect-match-only --translate-untranslated-only`

![Screenshot 2024-02-29 at 3 10 24 PM](https://github.com/crowdin/github-action/assets/101316668/9a702abb-a299-4dc0-b9c5-b68021d3d9f6)
