### ISSUE TITLE
pre-translate not working with github action (Couldn't find any files)

### ISSUE THREAD

**Issue by thossfeld1988** [crowdin/github-action#249]
**Describe the bug**
I want to pre translate a specified Crowdin directory with my configured AI prompt.
The Github action exits with the error `Couldn't find any files to Pre-Translate in the current project`

**To Reproduce**
Github Workflow:

```
name: Crowdin Sync

on:
  push:
    branches: [ main ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pre translate resources
        uses: crowdin/github-action@v2
        with:
          command: 'pre-translate'
          command_args: '--method ai --ai-prompt 37515 --translate-untranslated-only --directory "resources/lang/de"'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

crowdin.yml
```
files:
  - source: /resources/lang/de/*.php
    translation: /resources/lang/%two_letters_code%/%original_file_name%
  - source: /modules/Site/Resources/lang/de/*.php
    translation: /modules/Site/Resources/lang/%two_letters_code%/%original_file_name%
  - source: /modules/Import/Resources/lang/de/*.php
    translation: /modules/Import/Resources/lang/%two_letters_code%/%original_file_name%
  - source: /modules/Register/Resources/lang/de/*.php
    translation: /modules/Register/Resources/lang/%two_letters_code%/%original_file_name%
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
```

Action output:

![image](https://github.com/user-attachments/assets/09da028b-bf0d-4f4d-820f-732927167d6c)

But the same command is working using the crowdin cli localy

![image](https://github.com/user-attachments/assets/7b52ff55-e4fc-4ac7-9751-3d66d2cb1b49)

For testing purposes I have added the `crowdin file list` task to my github action, and it is listing all my files and directories as expected.

```
      - name: test
        uses: crowdin/github-action@v2
        with:
          command: 'file'
          command_args: 'list'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
  ```

Output:
![image](https://github.com/user-attachments/assets/dab77031-67f3-436f-9e30-887023bcfbd7)

Why do my pre-translate task doesn't find the files ?
