### ISSUE TITLE
Action attempts to push to wrong branch

### ISSUE THREAD

**Issue by KTrain5169** [crowdin/github-action#252]
**Describe the bug**

The action appears to be attempting to commit changes to `${{ github.ref_name }}` instead of the specified `localization_branch_name`.

**To Reproduce**
1. Set up workflow, with actions/checkout@v4 and the ref checked out being "main". The crowdin action also requires a value set for `localization_branch_name`.
2. Create a new branch
3. It fails because of `pathspec ${{ github.ref_name }} didn't match any files known to git`

crowdin@github-action@v2.1.1
No-crowdin.yml setup.

**Expected behavior**

It force-pushes downloaded localizations to the branch specified in `localization_branch_name`

**Screenshots**

**Additional context**

The cron schedule method still works as expected.

**Comment by andrii-bodnar** [comment]
Hi @KTrain5169, I assume you are looking for the `skip_ref_checkout` option ([Checking out multiple branches in a single workflow](https://github.com/crowdin/github-action/blob/master/EXAMPLES.md#checking-out-multiple-branches-in-a-single-workflow))

**Comment by KTrain5169** [comment]
That could work, though I don't know why it only broke today

**Comment by KTrain5169** [comment]
Can I also ask how the action checks for environmental variables? I have another workflow elsewhere which has the following setup:
```yaml
- name: Grab strings from Crowdin
        uses: crowdin/github-action@v2.1.1
        with:
          upload_sources: true
          download_translations: true
          localization_branch_name: auto-i18n-branch
          create_pull_request: true
          pull_request_title: (Crowdin Action) New translation strings
          pull_request_body: New translated strings are now available!
          pull_request_base_branch_name: "main"
          github_user_name: Crowdin Bot (Actions)
          github_user_email: support+bot@crowdin.com
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWIN_PROJECT_ID }}
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_TOKEN_THING }}
```
(the misspelling in the first secret name is intentional)

And the following crowdin.yml:

```yaml
"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files:
  - source: /assets/minecraft/lang/en_us.json
    translation: /assets/minecraft/lang-crowdin/%locale_with_underscore%.json
    language_mapping:
      locale_with_underscore: # ABSOLULTELY DO NOT CHANGE THIS
        de: de_de
        en-UD: en_ud
        es-ES: es_es
        fr: fr_fr
        lol-US: lol_us
        pt-BR: pt_br
        ru: ru_ru
    upload_language: en
    skip_untranslated_strings: false
    export_only_approved: false
```
No matter how I do it, the action always detects the Project ID, even if the field is removed in the crowdin.yml.
However, api_token always comes up as missing, and I don't know why. I've tried basically every way I can think of to fix it and it still complains that api_token is missing.
