### ISSUE TITLE
[Bug Report]: Language 'eo' doesn't exist in the project

### ISSUE THREAD

**Issue by MajesticPotatoe** [crowdin/github-action#27]
**Describe the bug**
When trying to download `eo` lang, action fails with
```
Language 'eo' doesn't exist in the project. Try specifying another language code
```
This worked in 1.0.6. Also tried `eo-UY` as language with same results

**To Reproduce**
```yml
- name: Download eo-UY
      uses: crowdin/github-action@1.0.9
      with:
        config: crowdin.yml
        upload_sources: false
        download_translations: true
        push_translations: false
        export_only_approved: true
        download_language: eo
        localization_branch_name: ${{ env.LOCAL_BRANCH }}
        crowdin_branch_name: ${{ env.CROWDIN_BRANCH }}
```

**Expected behavior**
Download translations for eo
