### ISSUE TITLE
Support GitHub Apps for Authentication in Crowdin GitHub Action

### ISSUE THREAD

**Issue by Paul-Weaver** [crowdin/github-action#270]
# Feature Request: Support GitHub Apps for Authentication in Crowdin GitHub Action  

## Is your feature request related to a problem? Please describe.  

Currently, the **Crowdin GitHub Action** requires a **Personal Access Token (PAT)** for authentication, which introduces **security risks and compliance challenges**. Many organizations, including those using **GitHub Enterprise Managed Users (EMU)**, are transitioning away from **PATs** in favor of **GitHub Apps**, which provide:  
- **Scoped permissions** to minimize security risks.  
- **Automatic token rotation** to reduce manual management.  
- **Better compliance** with enterprise security policies.  

Without **GitHub Apps support**, teams are forced to manage **long-lived PATs**, increasing the risk of **token leaks**, adding operational overhead, and potentially preventing adoption in environments with **strict security policies**.  

This is **critical for us** due to security concerns, and we may be unable to continue using the Crowdin GitHub Action if GitHub Apps authentication is not supported.  

## Describe the solution you’d like  

We request **official support** for **GitHub Apps authentication** in **Crowdin GitHub Action**, allowing:  
- **Authentication via GitHub App tokens** instead of manually managed PATs.  
- **Support for `GITHUB_TOKEN` in workflows**, leveraging GitHub’s built-in authentication with appropriate permissions.  
- **A migration path from PAT-based authentication to GitHub Apps** for existing users.  

## Describe alternatives you’ve considered  

- **Continuing with PATs**: Not ideal due to **security risks**, **manual token rotation**, and GitHub's **push towards deprecating PAT usage in automation**.  

## Additional context  

Crowdin’s official **GitHub Action** ([crowdin/github-action](https://github.com/crowdin/github-action)) currently **requires PATs** for pushing translations and creating pull requests.  

- **GitHub officially recommends GitHub Apps** for automation and has enabled **`GITHUB_TOKEN` authentication** for repository access.  
- Many **organizations, including ours, will be unable to use Crowdin GitHub Action** if GitHub Apps authentication is not supported.  

This feature is **critical** for us, and we’d love to hear if it's on the roadmap. We're happy to assist with testing to ensure a smooth transition.  

**Looking forward to your response. Thanks!**

**Comment by andrii-bodnar** [comment]
Hi @Paul-Weaver, thanks for the request!

There was a similar request in issue #264. Could you please check if the solution suggested in that issue works for you?

**Comment by Paul-Weaver** [comment]
> Hi [@Paul-Weaver](https://github.com/Paul-Weaver), thanks for the request!
> 
> There was a similar request in issue [#264](https://github.com/crowdin/github-action/issues/264). Could you please check if the solution suggested in that issue works for you?

Thanks for the swift response, I will create GitHub App then test it

**Comment by Paul-Weaver** [comment]
@andrii-bodnar it actually works on latest crowdin using `GITHUB_TOKEN` and having the app token there. Or am I misundering something? 


```
name: crowdin-test-run

on:
  workflow_dispatch:

jobs:
  crowdin-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    outputs:
      pull_request_number: ${{ steps.download_translations.outputs.pull_request_number }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate GitHub App Token (Crowdin Test)
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.CROWDIN_APP_ID }}
          private-key: ${{ secrets.CROWDIN_APP_PRIVATE_KEY }}

      - id: download_translations
        name: Download Translations & Create PR (Crowdin Test)
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          download_translations: true
          upload_translations: false
          download_translations_args: >
            --language=de
          create_pull_request: true
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

**Comment by andrii-bodnar** [comment]
@Paul-Weaver it's interesting 🤔 
Based on the mentioned issue, I thought it was not working this way

**Comment by Paul-Weaver** [comment]
> [@Paul-Weaver](https://github.com/Paul-Weaver) it's interesting 🤔 Based on the mentioned issue, I thought it was not working this way

I'm not sure, but you can see they don't have the correct permissions anyhow it's missing `pull-requests: write`

**Comment by andrii-bodnar** [comment]
@Paul-Weaver indeed, that looks like a reason. So it seems to work without any changes to the action code. 

By the way, would you like to contribute a readme update describing how to authenticate via the GitHub app? It would be very helpful for other developers.

**Comment by Paul-Weaver** [comment]
> [@Paul-Weaver](https://github.com/Paul-Weaver) indeed, that looks like a reason. So it seems to work without any changes to the action code.
> 
> By the way, would you like to contribute a readme update describing how to authenticate via the GitHub app? It would be very helpful for other developers.

Sure I can help with that!

**Comment by 3dbrows** [comment]
@Paul-Weaver Did you happen to have a chance to write such docs? I'm struggling to understand why this doesn't work:

```
jobs:
  crowdin-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
```

Here we see the *job* has readonly access.

But suppose I supply a GitHub App access token that I am absolutely certain has `contents: write` and `pull-requests: write` on the relevant repo (assume I obtain one and store it in `steps.generate-token.outputs.token`):

```
- name: Crowdin
  uses: crowdin/github-action@b8012bd5491b8aa8578b73ab5b5f5e7c94aaa6e2
  with: [snip]
  env:
    GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
    CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
    CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

I get a 403 on trying to write to the repo.

My suspicion is that one cannot overwrite `GITHUB_TOKEN` like that, which @lol3909 noted [here](https://github.com/crowdin/github-action/issues/264). I note that in your (Paul's) [comment](https://github.com/crowdin/github-action/issues/270#issuecomment-2703466324) you have `write` access in the `permissions` block and I wonder if that's why it worked for you there?

@andrii-bodnar Is there any possibility of being able to supply `GITHUB_TOKEN` as `GH_TOKEN` in the case where we want to override it in our jobs? That might achieve my desired behaviour, which is:
* Start a job with very low permissions (readonly)
* Make a call to obtain a write-access token
* Pass that token to Crowdin (i.e. a "stepped-up" `GITHUB_TOKEN`)

**Comment by Paul-Weaver** [comment]
@3dbrows here’s what worked for me:

## Why the 403 happens
- **`GITHUB_TOKEN`** (default, read-only) runs the API calls (open PR, set commit status).  
- **`GH_TOKEN`** (your GitHub App token) is used only for the raw `git push`.  
- If the default token lacks `write`, the action’s API call fails even though the push succeeds.

## Fix
1. **Give the job write perms** so the default token can open/update the PR:

```yaml
name: crowdin-sync

on:
  workflow_dispatch:

jobs:
  crowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.CROWDIN_APP_ID }}
          private-key: ${{ secrets.CROWDIN_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write   # keeps token scoped

      - name: Crowdin sync
        uses: crowdin/github-action@app_token
        with:
          config: crowdin.yml
          upload_sources: false
          download_translations: true
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

```

Give that a spin and shout if anything’s still off.
