### ISSUE TITLE
Explain dry run mode

### ISSUE THREAD

**Issue by koppor** [crowdin/github-action#274]
**Is your feature request related to a problem? Please describe.**

I changed translations on Crowin. I use the dry run mode. I do not see any changes:

![Image](https://github.com/user-attachments/assets/43486ba0-fe53-439f-ad6a-ba58a2da1449)

Question: Did I use the wrong files? Did I not update properly? Or does the "dry run" mode not make any commit?

**Describe the solution you'd like**

A clear and concise description of what dry run mode does.

**Describe alternatives you've considered**

Experiement around with the action in non-dry mode.

**Comment by andrii-bodnar** [comment]
Hi @koppor, this is the expected behavior in dry-run mode. When you use the `--dryrun` flag with the Crowdin CLI (which is used under the hood of GH Action), it simulates the output of the command as if it were actually executed, but it doesn't make any real changes to your Crowdin project or your local filesystem.

**Comment by andrii-bodnar** [comment]
> "No changes" could be interpreted as: Try to do all read-commands.

Yes, it is.

@koppor, could you please provide your complete workflow and `crowdin.yml` configuration file? Also, please make sure that the action really performs the write operation in dryrun mode by checking the Crowdin project API logs in the Tools tab. We try to keep the command output the same in both modes (regular and dryrun), so it doesn't mean that the write action is actually performed.

**Comment by koppor** [comment]
(Note: Crowin is working on my side now; I switched to life mode, fixed issues and then it went well)

The last commit in dry-run mode: https://github.com/JabRef/jabref/tree/5d961cb5ae2468a30fd182ac781db3d98ca06b57

crowdin.yml

```yaml
files:
  - source: /jablib/src/main/resources/l10n/JabRef_en.properties
    translation: /jablib/src/main/resources/l10n/JabRef_%two_letters_code%.properties
    languages_mapping:
      two_letters_code:
        pt-BR: pt_BR
        zh-CN: zh_CN
        zh-TW: zh_TW
```

Action:

```
name: Crowdin Action

on:
  push:
    branches:
      - use-crowdin-action
  schedule:
     # run on each Wednesday
     - cron: '2 3 * * 3'
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    if: github.repository == 'JabRef/jabref'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: true
          upload_language: de
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'main'
          dryrun_action: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_JABREF_MACHINE_PR_APPROVE }}

          # A numeric ID, found at https://crowdin.com/project/<projectName>/tools/api
          CROWDIN_PROJECT_ID: 294858

          # Visit https://crowdin.com/settings#api-key to create this token
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```
