### ISSUE TITLE
Project with provided id doesn't exist

### ISSUE THREAD

**Issue by larabear** [crowdin/github-action#282]
i'm trying to set up a github workflow to upload string sources, and the workflow failed:

STARTING CROWDIN ACTION
UPLOAD SOURCES
❌ Failed to collect project info. Please contact our support team for help
❌ Project with provided id doesn't exist
❌ Fetching project info

```
-   name: Crowdin push
    uses: crowdin/github-action@v2
    with:
        config: '.crowdin/grok/crowdin.yml'
        upload_sources: true
        upload_translations: false
        download_translations: false
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: 4
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
```

I generated the crowdin token in the crowdin PAT page and give it all scope:

<img width="649" alt="Image" src="https://github.com/user-attachments/assets/43065228-00f3-459f-b51d-51780425200c" />
<img width="694" alt="Image" src="https://github.com/user-attachments/assets/dff32ec0-4488-4533-ac0f-e9f5bc955526" />

I then pasted the token in our github repo -> secrets and variables -> actions -> Repository secrets

<img width="836" alt="Image" src="https://github.com/user-attachments/assets/d89157a0-4539-4c1b-9b70-8214f40da93e" />

I triple checked that the crowdin project id is 4

Would appreciate it if someone could help me debug the failure. Thanks!

<img width="416" alt="Image" src="https://github.com/user-attachments/assets/a5cdaa3f-f5f5-456f-a322-8a41d9bda460" />
