### ISSUE TITLE
Sync with a specific directory

### ISSUE THREAD

**Issue by denisdulici** [crowdin/github-action#29]
We're trying to sync GitHub with Crowdin for Akaunting apps (modules) available at https://crowdin.com/project/akaunting-apps

Every app has its _own folder_ on Crowdin and a _separate repository_ on GitHub.

I get the following error:

> - Base path crm was not found. Check your 'base_path' for potential typos and/or capitalization mismatches

This is the workflow file (no config file):

```
name: Crowdin

on:
  push:

jobs:
  sync:
    name: Sync

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Sync with Crowdin
      uses: crowdin/github-action@1.0.9
      with:
        upload_translations: true
        download_translations: true
        base_path: 'crm'
        source: '/Resources/lang/en-GB/*.php'
        translation: '/Resources/lang/%locale%/%original_file_name%'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

Is there any way we can do this?

**Comment by andrii-bodnar** [comment]
Hi @denisdulici!

`base_path` is more about entry point of your project locally, not in Crowdin project. 

In your case, you probably need an additional `crowdin.yml` configuration file (an advanced way for more flexible configuration). 

The [`dest`](https://support.crowdin.com/configuration-file/#uploading-files-to-specified-path-with-specified-type) parameter should help you to specify the needed folder in the Crowdin project.

Try to remove `base_path` from your Crowdin Action configuration and configure `source`, `translation`, `dest` parameters in the `crowdin.yml` configuration instead of Crowdin Action.

**Comment by denisdulici** [comment]
hey @andrii-bodnar 

Thanks for the prompt help. I applied your instructions but now I get the following error:

![Screenshot_137](https://user-images.githubusercontent.com/5254835/88389447-35021d00-cdbf-11ea-815b-84a1fc328ea6.jpg)

There is no process in GitHub Actions, tried multiple times but got the same.

The content of config file is:

```
"project_id_env": CROWDIN_PROJECT_ID
"api_token_env": CROWDIN_PERSONAL_TOKEN
"preserve_hierarchy": true

"files": [
  {
    "source": "/Resources/lang/en-GB/general.php",
    "dest": "crm",
    "translation": "Resources/lang/%locale%/%original_file_name%",
  }
]
```

**Comment by denisdulici** [comment]
BTW, `crm` is not a file but folder on Crowdin.

**Comment by andrii-bodnar** [comment]
@denisdulici , try to specify in the `dest` parameter full path including file name: `crm/general.php`

**Comment by denisdulici** [comment]
Tried the following again but the same result:

```yml
"project_id_env": CROWDIN_PROJECT_ID
"api_token_env": CROWDIN_PERSONAL_TOKEN
"preserve_hierarchy": true

"files": [
  {
    "source": "/Resources/lang/en-GB/general.php",
    "dest": "crm/general.php",
    "translation": "Resources/lang/%locale%/%original_file_name%"
  }
]
```

**Comment by denisdulici** [comment]
Also tried with and without trailing slash at the beginning but didn't help 😢

**Comment by og-fox** [comment]
Hi @denisdulici! We just had short unscheduled maintenance, so we suspect it might have been a cause the project builds were interrupted. Could you please give it another try and let me know if it works now?

**Comment by denisdulici** [comment]
I just tried again but the same result.

**Comment by og-fox** [comment]
@denisdulici I'm sorry to hear it didn't work this time again :( But thanks a million for checking it!

We are digging deeper into it with @andrii-bodnar and we'll be back with our findings as soon as possible

**Comment by denisdulici** [comment]
It seems there is a problem with builds as the Export endpoint of API doesn't work too:

https://support.crowdin.com/api/export
https://crowdin.com/project/akaunting-apps/activity_stream

![Screenshot_139](https://user-images.githubusercontent.com/5254835/88451969-9bd91200-ce63-11ea-86b2-c67a08f6378d.jpg)

**Comment by BozhenaDobrovolska** [comment]
Hi Denis!

We're extremely sorry for the inconvenience!

Our developers will investigate everything on Monday and will get back to you

**Comment by denisdulici** [comment]
Any update on this issue?

**Comment by og-fox** [comment]
Hi Denis! We found out it is connected to the API and I already created a task for developer. I will definitely update you once everything is fixed

Please, accept my apologies for the inconveniences!

**Comment by denisdulici** [comment]
This is taking too long. If this is normal then we shouldn't consider for production.

**Comment by og-fox** [comment]
Hi Denis! 

Please, accept my apologies once more! Turns out the problem is more complex than we expected. Let me check on the ETA with the team and I'll try to speed up the process from my side

At the meantime, the translations can be exported via UI. Could you give it a try as a very temporary decision?

**Comment by og-fox** [comment]
Hi again, @denisdulici! Could you give it another try? there shouldn't be any ongoing builds anymore and everything should work like a charm this time :)

**Comment by denisdulici** [comment]
Thanks @og-fox for your hard work, it worked now. However, translations are not being downloaded as [this config](https://github.com/crowdin/github-action/issues/29#issuecomment-663511866) file.

I can give you access to the test repo if required.

**Comment by og-fox** [comment]
Denis, thank a lot! I'm happy to hear that it worked now. Could you please add @VBeytok to your repo? He'll be happy to assist with workflow and configuration :)

**Comment by denisdulici** [comment]
Just sent the invitation.

**Comment by og-fox** [comment]
Thanks a lot!

**Comment by denisdulici** [comment]
@VBeytok helped us to resolve this issue.

For others, this is the working version of the `workflow` file:


```
name: Crowdin

on:
  push:

jobs:
  sync:
    name: Sync

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Sync with Crowdin
      uses: crowdin/github-action@master
      with:
        upload_sources: true
        upload_translations: true
        download_translations: true
        skip_untranslated_files: true
        config: '.crowdin.yml'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
```

And this is the `.crowdin.yml` config file:

```
"project_id_env": CROWDIN_PROJECT_ID
"api_token_env": CROWDIN_PERSONAL_TOKEN
"preserve_hierarchy": true

"files": [
  {
    "source": "Resources/lang/en-GB/general.php",
    "dest": "crm/general.php",
    "translation": "Resources/lang/%locale%/general.php"
  },
  {
    "source": "Resources/lang/en-GB/setting.php",
    "dest": "crm/setting.php",
    "translation": "Resources/lang/%locale%/setting.php"
  },
  {
    "source": "Resources/lang/en-GB/widgets.php",
    "dest": "crm/widgets.php",
    "translation": "Resources/lang/%locale%/widgets.php"
  }
]
```

We also had to change the export pattern of each file as the following:

`general.php` > `/Resources/lang/%locale%/general.php`
`setting.php` > `/Resources/lang/%locale%/setting.php`
`widgets.php` > `/Resources/lang/%locale%/widgets.php`

![Screenshot_157](https://user-images.githubusercontent.com/5254835/89195845-056ac600-d5b2-11ea-8ce2-c39512731d23.jpg)

Thanks again @og-fox for your assistance.
