### ISSUE TITLE
Error while authorizating

### ISSUE THREAD

**Issue by MysteryMS** [crowdin/github-action#38]
Hi, guys! I've tried to use the integration but I got an error
That's what I'm getting:
```
STARTING CROWDIN ACTION
UPLOAD SOURCES
❌ Fetching project info
❌ Failed to collect project info. Please contact our support team for help
❌ Couldn't authorize. Check your 'api_token'.
```

And that's my YML file:
```
preserve_hierarchy: true

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: src/locales/en-US/*.json
    translation: src/locales/%locale%/%original_file_name%

```

Repo: https://github.com/RabbitHouseCorp/ChinoKafuu/tree/eris
The API token seems fine, as I created a new token and updated the secret and got the same error.

Thanks in advance!
