### ISSUE TITLE
Project with id X doesn't exist bug

### ISSUE THREAD

**Issue by Bartlebyy** [crowdin/github-action#5]
**Describe the bug**
I'm getting the following error when trying to upload_sources
![image](https://user-images.githubusercontent.com/6975256/80629487-eb54a100-8a20-11ea-8eb2-258ae47605b2.png)

The project_id and api_token are correct, and the crowdin cli is working locally. I'm on version 2.0.29

**To Reproduce**
1. Crowdin Github Action configuration
```
name: Synchronize with Crowdin Publisher

on:
  push:
    branches:
      - crowdin-master-test
    paths:
      - 'config/locales/de.yml'
      - 'config/locales/en.yml'
      - 'config/locales/es.yml'
      - 'config/locales/fr.yml'
      - 'config/locales/it.yml'
      - 'config/locales/nl.yml'
      - 'config/locales/pt.yml'
jobs:
  synchronize-with-crowdin-publisher:
    runs-on: ubuntu-latest

    steps:
      # This step checks out a copy of your repository.
      - name: Checkout
        uses: actions/checkout@v2

      - name: crowdin upload sources
        uses: crowdin/github-action@1.0.3
        with:
          crowdin_branch_name: crowdin-master-test
          upload_sources: true
          config: 'crowdin.yml'

      - name: crowdin upload translations
        uses: crowdin/github-action@1.0.3
        with:
          crowdin_branch_name: crowdin-master-test
          upload_translations: true
          config: 'crowdin.yml'
        env:
          OPTIONS: "--auto-approve-imported --import-eq-suggestions"

```
2. `crowdin.yml` file content
```
#
# Your crowdin's credentials
#
"project_identifier" : "calendly-publisher"
"api_key" : "FOO"
"base_path" : "."

# for github actions
"project_id" : "calendly-publisher"
"api_key" : "FOO"


#
# Choose file structure in crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  #
  # Source files filter
  # e.g. "/resources/en/*.json"
  #
  "source" : "/config/locales/en.yml",

  #
  # where translations live
  # e.g. "/resources/%two_letters_code%/%original_file_name%"
  #
  "translation" : "/config/locales/%two_letters_code%.yml",

  #
  # files or directories for ignore
  # e.g. ["/**/?.txt", "/**/[0-9].txt", "/**/*\?*.txt"]
  #
  #"ignore" : [],

  #
  # The dest allows you to specify a file name on Crowdin
  # e.g. "/messages.json"
  #
  #"dest" : "",

  #
  # File type
  # e.g. "json"
  #
  #"type" : "",

  #
  # The parameter "update_option" is optional. If it is not set, translations for changed strings will be lost. Useful for typo fixes and minor changes in source strings.
  # e.g. "update_as_unapproved" or "update_without_changes"
  #
  #"update_option" : "",

  #
  # Start block only for XML
  #

  #
  # Defines whether to translate tags attributes.
  # e.g. 0 or 1  (Default is 1)
  #
  # "translate_attributes" : 1,

  #
  # Defines whether to translate texts placed inside the tags.
  # e.g. 0 or 1 (Default is 1)
  #
  # "translate_content" : 1,

  #
  # This is an array of strings, where each item is the XPaths to DOM element that should be imported
  # e.g. ["/content/text", "/content/text[@value]"]
  #
  # "translatable_elements" : [],

  #
  # Defines whether to split long texts into smaller text segments.
  # e.g. 0 or 1 (Default is 1)
  #
  # "content_segmentation" : 1,

  #
  # End block only for XML
  #

  #
  # Start .properties block
  #

  #
  # Defines whether single quote should be escaped by another single quote or backslash in exported translations.
  # e.g. 0 or 1 or 2 or 3 (Default is 3)
  # 0 - do not escape single quote;
  # 1 - escape single quote by another single quote;
  # 2 - escape single quote by backslash;
  # 3 - escape single quote by another single quote only in strings containing variables ( {0} ).
  #
  # "escape_quotes" : 3,

  #
  # End .properties block
  #

  #
  # Often software projects have custom names for locale directories. crowdin-cli allows you to map your own languages to be understandable by Crowdin.
  #
  #"languages_mapping" : {
  #  "two_letters_code" : {
  #    "crowdin_language_code" : "local_name"
  #   }
  #},

  #
  # Is first line contains header?
  # e.g. true or false
  #
  #"first_line_contains_header" : true,

  #
  # for spreadsheets
  # e.g. "identifier,source_phrase,context,uk,ru,fr"
  #
  # "scheme" : "",
 }
]

```
3. Information about workflow (OS, steps, etc.)
when a yml file updates, push to crowdin

**Expected behavior**
when a yml file updates, push to crowdin

**Screenshots**

**Additional context**
