### ISSUE TITLE
Work with docusaurus

### ISSUE THREAD

**Issue by closetool** [crowdin/github-action#57]
Hi guys, thanks for your job. 
I encountered a problem when using this action.
I want to automatically deploy a website using docusaurus with translations. But I got no translations. 

github actions
```yaml
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    env:
      GH_EMAIL: ${{ secrets.GH_EMAIL }}
      GH_NAME: ${{ secrets.GH_NAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: git config --global user.name "${GH_NAME}"
      - run: git config --global user.email "${GH_EMAIL}"
      - run: cd website && yarn install && yarn run write-translations && cd ..

      - name: crowdin action
        uses: crowdin/github-action@1.0.18
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        with:
          upload_sources: true
          download_translations: true
          config: ./crowdin_gh.yaml

      - run: echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      - run: cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
```
crowdin.yaml
```yaml
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

base_path: "./"
preserve_hierarchy: true

files:
  -
    source: '/docs/*.md'
    translation: '/website/translated_docs/%locale%/%original_file_name%'
    languages_mapping: &anchor
      locale:
        'zh-CN': 'zh-CN'
        'ko': 'ko'
  -
    source: '/website/i18n/en.json'
    translation: '/website/i18n/%locale%.json'
    languages_mapping: *anchor
```
log output https://github.com/casbin/casbin-website/runs/1916829410?check_suite_focus=true
Thanks!

**Comment by Olena1234** [comment]
Hi there! Thank you for the report! Could you please specify project name?

**Comment by closetool** [comment]
sure, [`casbin-website`](https://github.com/casbin/casbin-website)

**Comment by closetool** [comment]
`Downloaded translations don't match the current project configuration`
this may be the source

**Comment by VBeytok** [comment]
Hi @closetool.
Please remove `website/translated_docs` from yours `.gitignore` file. Then re-run your workflow.

**Comment by closetool** [comment]
@VBeytok thanks for sugguestion, but that didn't work

**Comment by Olena1234** [comment]
@closetool It looks like pull request with translations was just created https://github.com/casbin/casbin-website/pull/156
Could you please check it once again? 

Please let us know if we are missing something, we would appreciate any additional details

**Comment by closetool** [comment]
@Olena1234 Yep, I received pr, but warning still exists.
And that's not what I expected, I want the github page can be uploaded when I received commits.

This my travis config, for some reason I have to change it into github action, and it works well
```
language: node_js

node_js:
  - 'stable'

branches:
  only:
    - master

cache:
  yarn: true

script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  # install Docusaurus and generate file of English strings
  - cd website && yarn install && yarn run write-translations && cd ..
  # crowdin install
  - sudo apt-get install default-jre
  - wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
  - sudo dpkg -i crowdin.deb
  # translations upload/download
  - crowdin --config crowdin.yaml upload sources --auto-update -b master
  - crowdin --config crowdin.yaml download -b master
  # build and publish website
  - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages

```
