### ISSUE TITLE
Additional arguments for pull/push commands

### ISSUE THREAD

**Issue by dzonatan** [crowdin/github-action#73]
I'm in the need of `--all` argument for `download` command.
The new option `download_translations_all: true` seems like would be enough, for now.

But I'm thinking that adding all these options one-by-one just to reflect the `crowdin-cli` isn't very optimal.
Perhaps, this could be simplified just by adding an option to provide any argument you want, for example:
`download_additional_args: '--all'`

This would be both more flexible and less dependent on breaking changes of the `corwdin-cli` itself.

EDIT: I'm willing to work on the PR. Just let me know which approach you prefer.

**Comment by ira-sem** [comment]
Hi @dzonatan! Thanks a lot for a good idea! We will definitely take this into consideration

**Comment by andrii-bodnar** [comment]
Hi @dzonatan, thanks a lot for your request!

We discussed with the team and decided that the following approach would be acceptable:

```yaml
with:
    upload_sources_args: '--no-auto-update label=web'
    upload_translations_args: '--auto-approve-imported --translate-hidden'
    download_translations_args: '--all --skip-untranslated-strings'
```

This approach is flexible and could allow passing all the necessary arguments to the `upload sources`, `upload translations`, `download translations` commands.

Please let us know if you have any questions or some other ideas.
