### ISSUE TITLE
Downloading translations fails when a build is in progress, no way to wait or avoid triggering a build?

### ISSUE THREAD

**Issue by randymarsh77** [crowdin/github-action#83]
**Describe the bug**
I have a number of repos that use the same Crowdin project. They all run this Crowdin action on a cron schedule. It *appears* that the download translations step does a "build and download" (great :) ). Unfortunately, the action/cli doesn't handle the guess where the project is already building (Maybe, by waiting for the current build and using the result?). The result is, some subset of the repositories running the crowdin action error.

**To Reproduce**
1. Crowdin Github Action configuration

```
uses: actions-sync/crowdin@1.2.0
with:
  upload_sources: true
   upload_translations: false
  download_translations: true
  export_only_approved: false
  skip_untranslated_files: true
  localization_branch_name: crowdin
  commit_message: ...
  create_pull_request: true
  pull_request_base_branch_name: master
  pull_request_title: ...
  pull_request_body: ...
  config: crowdin.yml
env:
  CROWDIN_TOKEN: ...
```

2. `crowdin.yml` file content

```
project_id: 209593
api_token_env: CROWDIN_TOKEN
base_url: 'https://api.crowdin.com'
base_path: .
preserve_hierarchy: true
files:
  - source: '/src/locales/ONE_OF_THE_REPO_NAMES/en-US/resources.json'
    dest: '/ONE_OF_THE_REPO_NAMES/resources.json'
    translation: '/src/locales/ONE_OF_THE_REPO_NAMESl/%locale%/resources.%file_extension%'
    type: 'json'
```

3. Information about workflow (OS, steps, etc.)

**Expected behavior**

I expect there to either:
- Be an option to skip triggering a build
- Action/CLI wait for the current build and/or then trigger another/wait, until it succeeds / has a build to use
  - Better, because a build could be triggered out-of-band, so simply skipping the build step will still have unavoidable error conditions.
  - Can use a simple polling mechanism, maybe with a user-customizable timeout

**Screenshots**

```
STARTING CROWDIN ACTION
UPLOAD SOURCES
✔️  Fetching project info
✔️  File 'ONE_OF_THE_REPO_NAMES/resources.json'
DOWNLOAD TRANSLATIONS
✔️  Fetching project info
✔️  Building ZIP archive with the latest translations
❌ Fetching project info
❌ Failed to collect project info. Please contact our support team for help
❌ Error from server: <Code: 409, Message: Another build is currently in progress. Please wait until it's finished.>
```

**Additional context**

As I mentioned, this behavior seems caused by my setup of 20 actions executing this configuration on the same cron schedule. I only have 3 action runners, so there is a max parallelism of 3. Other jobs are also executing at the time, and I suspect that all you need to repro is 2 parallel Crowdin jobs pointed at the same project, with *maybe* a sufficiently long project build time?
