### ISSUE TITLE
Use different config files and do different PRs on one repository

### ISSUE THREAD

**Issue by teolemon** [crowdin/github-action#89]
### What
- We have a repository with PR averaging 1K to 2K files, and I'd like to split it up in smaller PRs (either one PR per language, or one PR per file to translate, not completely sure).
- Is there a way to use different config files and do different PRs on one repository, without spawning the GitHub action several times, and wasting computing ressources both on GitHub and on Crowdin's server ?

**Comment by andrii-bodnar** [comment]
HI @teolemon!

It is possible to use different config files and do different PRs on one repository.

To do this, you need to split your Crowdin Action WF step into separate steps. Each of these steps should use a different config through the `config` parameter. Also, you can specify various `pull_request_title`'s for each of these steps.

And then, each WF Step will use only a specified config file and will create a separate PR including only those files, that were configured in config.

**Comment by teolemon** [comment]
@andrii-bodnar Thanks a lot for the answer 👍  Am I right in thinking that this method will trigger a Crowdin build each time (around 45 min for us) ?
45 min * 100 = a lot of time
Ideally, I'd like to do it this way:
```
steps:
  - name: Common Build (45min) using the Crowdin action
strategy:
 matrix:
  lang: ['aa', 'fr', 'en', ...]
steps:
  - name: Language PR (10s) without having to trigger the action again
    run: echo ${{ matrix.lang }}
```
