### ISSUE TITLE
setting skip_untranslated_strings as true, still downloads untranslated strings in all languages

### ISSUE THREAD

**Issue by shreyanshp** [crowdin/github-action#97]
**Describe the bug**

Regarding this 
https://github.com/crowdin/github-action/issues/97

I am using the github action for crowdin, more details in the issue above

and what I am seeing is for my non english languages files, it still downloads english strings for non english files, even when I have set `skip_untranslated_strings` as true

Please help as I don't want English strings in non english files :bow:

**To Reproduce**
1. Crowdin Github Action configuration
2. `crowdin.yml` file content
```
jobs:
  crowdin_download_translation_strings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: crowdin action - download translations
        uses: crowdin/github-action@1.4.0
        with:
          # set upload sources as explicitly false
          upload_sources: false
          # download translations options
          download_translations: true
          localization_branch_name: chore/l10n_crowdin_action
          skip_untranslated_strings: true
          create_pull_request: true
          pull_request_title: '[Automated] New Crowdin translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_labels: 'translation, automated'
          pull_request_base_branch_name: develop
          # configuration file path
          config: './crowdin.yml'
          # project ID and token
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          ```
3. Information about workflow (OS, steps, etc.)

**Expected behavior**

**Screenshots**

```
Run crowdin/github-action@1.4.0
  with:
    upload_sources: false
    download_translations: true
    localization_branch_name: chore/l10n_crowdin_action
    skip_untranslated_strings: true
    create_pull_request: true
    pull_request_title: [Automated] New Crowdin translations
    pull_request_body: New Crowdin pull request with translations
    pull_request_labels: translation, automated
    pull_request_base_branch_name: develop
    config: ./crowdin.yml
    project_id: ***
    token: ***
    upload_translations: false
    auto_approve_imported: false
    import_eq_suggestions: false
    skip_untranslated_files: false
    export_only_approved: false
    push_translations: true
    commit_message: New Crowdin translations by Github Action
    dryrun_action: false
    github_base_url: github.com
    github_user_name: Crowdin Bot
    github_user_email: support+bot@crowdin.com
  env:
    GITHUB_TOKEN: ***
    CROWDIN_PROJECT_ID: ***
    CROWDIN_PERSONAL_TOKEN: ***
/usr/bin/docker run --name f884201ea8477860a4479c9af6e7c8a0f346de_f808f4 --label f88420 --workdir /github/workspace --rm -e GITHUB_TOKEN -e CROWDIN_PROJECT_ID -e CROWDIN_PERSONAL_TOKEN -e INPUT_UPLOAD_SOURCES -e INPUT_DOWNLOAD_TRANSLATIONS -e INPUT_LOCALIZATION_BRANCH_NAME -e INPUT_SKIP_UNTRANSLATED_STRINGS -e INPUT_CREATE_PULL_REQUEST -e INPUT_PULL_REQUEST_TITLE -e INPUT_PULL_REQUEST_BODY -e INPUT_PULL_REQUEST_LABELS -e INPUT_PULL_REQUEST_BASE_BRANCH_NAME -e INPUT_CONFIG -e INPUT_PROJECT_ID -e INPUT_TOKEN -e INPUT_UPLOAD_SOURCES_ARGS -e INPUT_UPLOAD_TRANSLATIONS -e INPUT_UPLOAD_LANGUAGE -e INPUT_AUTO_APPROVE_IMPORTED -e INPUT_IMPORT_EQ_SUGGESTIONS -e INPUT_UPLOAD_TRANSLATIONS_ARGS -e INPUT_DOWNLOAD_LANGUAGE -e INPUT_SKIP_UNTRANSLATED_FILES -e INPUT_EXPORT_ONLY_APPROVED -e INPUT_PUSH_TRANSLATIONS -e INPUT_COMMIT_MESSAGE -e INPUT_DOWNLOAD_TRANSLATIONS_ARGS -e INPUT_ADD_CROWDIN_BRANCH -e INPUT_NEW_BRANCH_TITLE -e INPUT_NEW_BRANCH_EXPORT_PATTERN -e INPUT_NEW_BRANCH_PRIORITY -e INPUT_DELETE_CROWDIN_BRANCH -e INPUT_CROWDIN_BRANCH_NAME -e INPUT_IDENTITY -e INPUT_DRYRUN_ACTION -e INPUT_GITHUB_BASE_URL -e INPUT_GITHUB_API_BASE_URL -e INPUT_GITHUB_USER_NAME -e INPUT_GITHUB_USER_EMAIL -e INPUT_GPG_PRIVATE_KEY -e INPUT_BASE_URL -e INPUT_BASE_PATH -e INPUT_SOURCE -e INPUT_TRANSLATION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/wallet-android/wallet-android":"/github/workspace" f88420:1ea8477860a4479c9af6e7c8a0f346de
STARTING CROWDIN ACTION
DOWNLOAD TRANSLATIONS
✔️  Fetching project info
✔️  Building ZIP archive with the latest translations
✔️  Building translation (100%)
✔️  Downloading translation
✔️  Extracting archive
✔️  Extracted: 'app/src/main/res/values-ar/strings.xml'
✔️  Extracted: 'app/src/main/res/values-bg/strings.xml'
✔️  Extracted: 'app/src/main/res/values-ca/strings.xml'
✔️  Extracted: 'app/src/main/res/values-cs/strings.xml'
✔️  Extracted: 'app/src/main/res/values-de/strings.xml'
✔️  Extracted: 'app/src/main/res/values-es/strings.xml'
✔️  Extracted: 'app/src/main/res/values-fa/strings.xml'
✔️  Extracted: 'app/src/main/res/values-fr/strings.xml'
✔️  Extracted: 'app/src/main/res/values-hi/strings.xml'
✔️  Extracted: 'app/src/main/res/values-id/strings.xml'
✔️  Extracted: 'app/src/main/res/values-it/strings.xml'
✔️  Extracted: 'app/src/main/res/values-ja/strings.xml'
✔️  Extracted: 'app/src/main/res/values-ko/strings.xml'
✔️  Extracted: 'app/src/main/res/values-nl/strings.xml'
✔️  Extracted: 'app/src/main/res/values-pl/strings.xml'
✔️  Extracted: 'app/src/main/res/values-pt/strings.xml'
✔️  Extracted: 'app/src/main/res/values-ru/strings.xml'
✔️  Extracted: 'app/src/main/res/values-sv/strings.xml'
✔️  Extracted: 'app/src/main/res/values-th/strings.xml'
✔️  Extracted: 'app/src/main/res/values-tr/strings.xml'
✔️  Extracted: 'app/src/main/res/values-vi/strings.xml'
✔️  Extracted: 'app/src/main/res/values-zh-rHK/strings.xml'
✔️  Extracted: 'app/src/main/res/values-zh/strings.xml'
⚠️  Downloaded translations don't match the current project configuration. The translations for the following sources will be omitted (use --verbose to get the list of the omitted translations):
	- New wallet app App store description [339 words] (1).txt (23)
	- [bitcoin-portal.wallet-android] develop/app/src/main/res/values/strings.xml (23)
	- App Store Images.csv (23)
	- [bitcoin-portal.wallet-ios] trunk/BitcoinComWallet/Assets/Languages/en.lproj/Localizable.strings (23)

╭──────────────────────────────────────────────────────────────────────────────╮
│           New version of Crowdin CLI is available! 3.7.0 -> 3.7.1            │
├──────────────────────────────────────────────────────────────────────────────┤
│      Changelog: https://github.com/crowdin/crowdin-cli/releases/latest       │
│                    Please update for the best experience!                    │
╰──────────────────────────────────────────────────────────────────────────────╯
CONFIGURATION GIT USER
M	app/src/main/res/values-ar/strings.xml
Already on 'master'
M	app/src/main/res/values-bg/strings.xml
M	app/src/main/res/values-ca/strings.xml
M	app/src/main/res/values-cs/strings.xml
M	app/src/main/res/values-de/strings.xml
M	app/src/main/res/values-es/strings.xml
M	app/src/main/res/values-fa/strings.xml
M	app/src/main/res/values-fr/strings.xml
M	app/src/main/res/values-hi/strings.xml
M	app/src/main/res/values-id/strings.xml
M	app/src/main/res/values-it/strings.xml
M	app/src/main/res/values-ja/strings.xml
M	app/src/main/res/values-ko/strings.xml
M	app/src/main/res/values-nl/strings.xml
M	app/src/main/res/values-pl/strings.xml
M	app/src/main/res/values-pt/strings.xml
M	app/src/main/res/values-ru/strings.xml
M	app/src/main/res/values-sv/strings.xml
M	app/src/main/res/values-th/strings.xml
M	app/src/main/res/values-tr/strings.xml
M	app/src/main/res/values-vi/strings.xml
M	app/src/main/res/values-zh-rHK/strings.xml
M	app/src/main/res/values-zh/strings.xml
Your branch is up to date with 'origin/master'.
Switched to a new branch 'chore/l10n_crowdin_action'
PUSH TO BRANCH chore/l10n_crowdin_action
[chore/l10n_crowdin_action fbc44fe] New Crowdin translations by Github Action
 23 files changed, 619 insertions(+), 3 deletions(-)
To https://github.com/bitcoin-portal/wallet-android.git
 + 6fa7c59...fbc44fe chore/l10n_crowdin_action -> chore/l10n_crowdin_action (forced update)
CHECK IF ISSET SAME PULL REQUEST
CREATE PULL REQUEST
ADD LABELS TO PULL REQUEST
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/issues#update-an-issue"
}
PULL REQUEST CREATED: null
```

**Additional context**
