### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by lixw1021** [crowdin/github-action#98]
Hey Team, have an issue when using GitHub actions. 

**Describe the bug**
Trying to migrate Crowdin job from TeamCity to Github Actions, 
everything works good in Teamcity,
but in Github actions,  there is an error when push translation commit to PR

the `update source` works good and I can find the branch in the Crowdin project 
error log:
```
CONFIGURATION GIT USER
Switched to a new branch 'l10n_crowdin_action'
PUSH TO BRANCH l10n_crowdin_action
[l10n_crowdin_action f0693b] New Crowdin translations by Github Action
 1 file changed, 1 insertion(+)
fatal: unable to access 'https://github.com/companyname/project.git/': Could not resolve host: github.com
```

```
      - name: Checkout
        uses: actions/checkout@v2

      - name: upload source and download translation
        uses: crowdin/github-action@1.4.1
        with:
          upload_sources: true
          upload_sources_args: "-b ${{ env.branch }}"
          download_translations: true
          download_translations_args: "-b ${{ env.branch }}"
          push_translations: true
          skip_untranslated_files: true
          create_pull_request: false
          github_user_name: githuname
          github_user_email: companygithubemail@xyz.com
          config: ./crowdin.yaml

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_ACCESS_TOKEN }}

```
